Catappult/appcoins-wallet-android

app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
app/src/main/java/com/asfoundation/wallet/topup/TopUpItemDecorator.kt
app/src/main/java/com/asfoundation/wallet/ui/appcoins/CardNotificationsItemDecorator.kt

On a previous PR while extracting dpToPx conversions to an extension function, some other conversions were extracted too. This PR aims to revert those.
This was visible in the notification cards when there were no transactions.
No
CardNotificationsItemDecorator.kt
Check if the cards on home without transactions appear correctly
https://aptoide.atlassian.net/browse/WAL-104
**Questions:**

[WAL-104] Rever changes made on DP conversion

---

app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java

Bugfix related to not showing the right reason why AppCoins / AppCoins Credits option is disabled in In-App purchase flow. The following changes were made:
- When user has enough AppCoins to buy the item, but doesn't have AppCoins Credits nor ETH to pay the fee, message to display was changed to indicate that user doesn't have ETH
- When user doesn't have enough AppCoins nor AppCoins Credits (independently of having ETH or not), the message to display was changed to indicate that user doesn't have enough funds
No
Check if above use cases are working as intended. Check if other use cases related to inability to use APPC in IAP were not broken.
**What are the relevant …

[WAL-82] Check no balance: APPC and APPC-C

---

app/build.gradle
app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressFragment.kt
app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressModule.kt
app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressPresenter.kt
app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressRepository.kt
app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressView.kt
app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
app/src/main/java/com/asfoundation/wallet/di/InteractorModule.kt
app/src/main/java/com/asfoundation/wallet/di/RepositoryModule.kt
app/src/main/java/com/asfoundation/wallet/repository/SecureSharedPreferences.kt
app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpFragment.kt
app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpModule.kt
app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpPresenter.kt
app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpView.kt
app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
app/src/main/java/com/asfoundation/wallet/util/ExtensionFunctionUtils.kt
app/src/main/res/layout-land/layout_billing_address.xml
app/src/main/res/layout/layout_billing_address.xml
build.gradle

This PR saves billing address when inputted correctly and auto-fills it for the next purchase. This info is encrypted with the androidx.security library.
No
Get an Adyen test card and a proxy to US. Then simply make two credit card purchases. For the second purchase, it should remember the billing address info.
[WAL-131](https://aptoide.atlassian.net/browse/WAL-131)
**Notes:**
It adds the "new" androidx.security library. Please note that the version is in alpha for a good reason: it is the version that supports API 21 and 22 (the other RC only supports 23+).

[feature/WAL-131] Billing Address remembered

---

app/src/main/java/com/asfoundation/wallet/topup/TopUpSuccessFragment.kt

Fixes issue where we're showing the bonus animation when there was no bonus on topup
No
TopUpSuccessFragment.kt
Do a topup with a partner user wallet
https://aptoide.atlassian.net/browse/WAL-149

[WAL-149] Show no bonus animation when there's no bonus on topup

---

app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt

Fixes problems with previous implementation:
Adds the rules of not showing the amount string on iap and adds the rule of showing the payment rule before the amount rule 
No
AdyenPaymentPresenter.kt
AdyenTopUpPresenter.kt
Check if with a inapp purchase with a high amount 10€, you get the code, but it doesn't show the message
The other rule, I don't remember any possible test
https://aptoide.atlassian.net/browse/APPC-2171

[APPC-2171] Implemented rules that were missing, specified in the ticket

---

app/src/main/java/com/asfoundation/wallet/di/InteractorModule.kt
app/src/main/java/com/asfoundation/wallet/interact/TransactionViewInteractor.kt
app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
app/src/main/java/com/asfoundation/wallet/promotions/PromotionsPresenter.kt
app/src/main/java/com/asfoundation/wallet/repository/PreferencesRepositoryType.kt
app/src/main/java/com/asfoundation/wallet/repository/SharedPreferencesRepository.kt
app/src/main/java/com/asfoundation/wallet/ui/TransactionsActivity.java
app/src/main/java/com/asfoundation/wallet/ui/overlay/OverlayData.kt
app/src/main/java/com/asfoundation/wallet/ui/overlay/OverlayFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/overlay/OverlayInteractor.kt
app/src/main/java/com/asfoundation/wallet/ui/overlay/OverlayModule.kt
app/src/main/java/com/asfoundation/wallet/ui/overlay/OverlayPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/overlay/OverlayType.kt
app/src/main/java/com/asfoundation/wallet/ui/overlay/OverlayView.kt
app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsInteractor.kt
app/src/main/java/com/asfoundation/wallet/viewmodel/TransactionsViewModel.java

Implements displaying of tooltip highlighting new vouchers feature. The tooltip is always shown after the promotions tooltip, and for new installs, before fingerprint tooltip.
No
Here is a list of use cases that you can test, individually:
- Fresh install. Open app. Promotions tooltip -> Dismiss. Close app and reopen. E-vouchers tooltip -> Dismiss / Discover. Close app and reopen. Fingerprint tooltip.
- Fresh install. Open app. Promotions tooltip -> Discover. Close app and reopen. E-vouchers tooltip not shown because user has already gone to promotions screen. Close app and reopen. Fingerprint Notification.
- Update from a version without e-vouchers tooltip, where …

[APPC-2249] E-voucher - Implement tooltip

---

app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt

Adds logic to display a new error message in Top Up when list of risk rule codes contains both codes currently being matched. The new message gives more options to the user regarding what he/she can do.
No
Using prod version, and a card (you can pm me for the specific card), try to do a Top Up and see if the error message displayed is the newly added one.
Tickets related to this pull-request: [APPC-2260](https://aptoide.atlassian.net/browse/APPC-2260)
**Questions:**
Answer: No

[APPC-2260] Improve error message for fraud specific cases: part ii

---

app/src/main/java/com/asfoundation/wallet/ui/onboarding/OnboardingActivity.kt
app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
app/src/main/java/com/asfoundation/wallet/util/ExtensionFunctionUtils.kt

Adds "lang" parameter to myappcoins page (redeem codes), to show page in language used by wallet, and not the one used by browser.
Adds notes to other pages that will be moved to myappcoins, to remeber to add lang parameter to these
No
- SettingsFragment.kt
Change the default language of the browser, to be different than the one used in the wallet app.
Open wallet app -> Go to settings -> Redeem Code -> The myappcoins page should be displayed in the language used in wallet (if translations are available), not the one used by the browser.
Test both on dev and prod.
Tickets related to this pull-request: …

[APPC-2222] MyAppcoins and lang parameter

---

app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/payments/common/PurchaseBonusView.kt

Fixes 2 bugs related to bonus view:
- Bonus message was appearing with % to partner users after they had some pre selected methods (described in ticket)
- Bonus visibility switch when switching between earn appc and other payment methods.
No
PaymentMethodsPresenter.kt
PurchaseBonusView.kt
With a partner user, make a purchase with APPC-C, then after it's preselected, click on other payment methods and check if the bonus message doesn't appear.
The other fix, requires changing the code, since at the moment the "Earn appcoins" method doesn't appear. But to test change on the handleBonusVisiblity the EARN_APPC for CREDIT_CARD, this way Credit card method behaves just …

[APPC-2301] Empty bonus for partners users from pre selected

---

app/src/main/java/com/asfoundation/wallet/verification/intro/VerificationIntroPresenter.kt

Fixes issue where rotating the screen on VerifyIntroFragment after a no network error was shown was not not loading correctly after rotating back.
No
Go to an unverified wallet, go to verify, turn off WiFi and rotate the screen. A no network error should appear. Then, turn on WiFi back again and rotate the screen. It should now load normally.
[APPC-2383](https://aptoide.atlassian.net/browse/APPC-2383)

[bugfix/APPC-2383] Fix for no network screen after rotating verify screen

---

app/src/main/java/com/asfoundation/wallet/subscriptions/SubscriptionItem.kt
app/src/main/java/com/asfoundation/wallet/subscriptions/SubscriptionViewHolder.kt
app/src/main/java/com/asfoundation/wallet/subscriptions/UserSubscriptionsLocalData.kt
app/src/main/java/com/asfoundation/wallet/subscriptions/UserSubscriptionsMapper.kt
app/src/main/java/com/asfoundation/wallet/subscriptions/cancel/SubscriptionCancelPresenter.kt
app/src/main/java/com/asfoundation/wallet/subscriptions/details/SubscriptionDetailsFragment.kt
app/src/test/java/com/asfoundation/wallet/subscriptions/UserSubscriptionsMapperTest.kt
bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/subscriptions/UserSubscriptionResponse.kt

Includes fixing of unit tests to consider this.
This does not include any UI / updates.
Supporting new states (GRACE and HOLD) for subscriptions. Updated field name to be consistent with API.
No
For the new field name, test with a wallet that has an expired subscription (e.g. cancelled and expiration date has been reached). Without this PR, the wallet would crash (because field name is outdated).
For the new states, you can manually add code to see if GRACE subscriptions appear as active (HOLD should not). Other than that, there's not much that can be tested I think. You should, however, run the updated unit tests on `UserSubscriptionsMapper`
**What are the relevant …

[APPC-2365] Expire field rename. GRACE and HOLD status added

---

app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
app/src/main/java/com/asfoundation/wallet/rating/RatingInteractor.kt
app/src/main/java/com/asfoundation/wallet/support/SupportInteractor.kt
app/src/main/java/com/asfoundation/wallet/ui/gamification/SharedPreferencesUserStatsLocalData.kt
app/src/main/java/com/asfoundation/wallet/ui/onboarding/OnboardingInteractor.kt
gamification/schemas/com.appcoins.wallet.gamification.repository.PromotionDatabase/4.json
gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
gamification/src/main/java/com/appcoins/wallet/gamification/repository/PromotionDao.kt
gamification/src/main/java/com/appcoins/wallet/gamification/repository/PromotionDatabase.kt
gamification/src/main/java/com/appcoins/wallet/gamification/repository/UserStatsLocalData.kt
gamification/src/main/java/com/appcoins/wallet/gamification/repository/WalletOriginDao.kt
gamification/src/main/java/com/appcoins/wallet/gamification/repository/entity/PromotionEntity.kt
gamification/src/test/java/com/appcoins/wallet/gamification/UserStatsDataTest.kt

Fix issue related to only 1 perk being displayed with wifi off, even when there are multiple ones. The fix involved changing the primary key of the DB table to one that is 100% unique for each promotion. As such, it also involved a database migration.
Furthermore, another bugfix was done in this PR: an issue where two wallet origins (type of user - APTOIDE, PARTNER, UNKNOWN) were being saved for the same wallet address. This only happened for the wallet created on the Onboarding Process (for wallets created on the balance screen or recovered wallets, this was not an issue). One of them (used just in Onboarding) had uppercase characters, but everywhere else it's the lowercase wallet address that is used. The fix was the following: when retrieving wallet origin, …

[APPC-2407] [Perks] Only 1 Perk is shown with WiFi off

---

app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
app/src/main/res/xml/fragment_settings.xml

Signed-off-by: Trinkes <fabiojscosta1583@gmail.com>
Hide withdraw screen while it's not production ready
No
**Questions:**

hide withdraw screen while it's not production ready

---

app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyPresenter.kt

There was a bug introduced with APPC-2525 that essentially APPC-C IAPs were getting stuck in loading even after they were completed. This PR addresses that.
No
Teste if APPC-C IAPs now work correctly.
[APPC-2598](https://aptoide.atlassian.net/browse/APPC-2598)

[bugfix/APPC-2598] APPC-C IAP stuck even after completed

---

gamification/src/main/java/com/appcoins/wallet/gamification/repository/PromotionConverter.kt

Fixes an issue where users with max level was seeing negative AppCoins or 0 appcoins to reach next level (even though there's no next level).
No
Check with a wallet address with max level on promotions screen if it doesn't show the "0 AppCoins to reach next level" message.
[APPC-2588](https://aptoide.atlassian.net/browse/APPC-2588)

[bugfix/APPC-2588] Fixed issue with max level users seeing negative AppCoins

---

app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
app/src/main/res/layout/merged_appcoins_layout.xml

This PR fixes an issue where APPC/APPC-C options in IAP dialog was not respecting the order in webservice. It also changes the order from APPC -> APPC-C to APPC-C -> APPC in the MergedAppcoinsFragment screen.
No
Check that the payment methods order being shown in the IAP now respects the webservice. Also check that the order in MergedAppCoinsFragment screen is APPC-C then APPC.
[APPC-2658](https://aptoide.atlassian.net/browse/APPC-2658)

[task/APPC-2658] IAP Appc/Appc-c respect webservice order 

---

app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
app/src/main/res/layout/credits_radio_button.xml

- alters appcoins credits icon size
- alters name of AppCoins option in payment_methods
No
- check if “AppCoins (APPC)/AppCoins Credits“ payment_method option is now  “AppCoins Credits/AppCoins (APPC)“
- check if icon size of APPC-C is the same size as the APPC icon in payment_methods.
Tickets related to this pull-request: [APPC-2686](https://aptoide.atlassian.net/browse/APPC-2686)
**Questions:**
No.

[bugfix/APPC-2686] Change name and icon

---

app/src/main/res/layout-land/merged_appcoins_layout.xml
app/src/main/res/layout-land/payment_methods_layout.xml

- removes visibility of loading from payments_methods land
- switches position of APPC with APPC-C in payment_methods land
No
- check if there is no loading animation behind the skeleton on the payments screen
- check if the payments order is APPC Credits first and then APPC in the  payments screen
Tickets related to this pull-request: [APPC-2690](https://aptoide.atlassian.net/browse/APPC-2690)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.) 
No.

[bugfix/APPC-2690] Removes Payments Landscape Loading

---

skills/src/main/java/cm/aptoide/skills/games/BackgroundGameService.kt

For that, uses IMPORTANCE_LOW instead of IMPORTANCE_HIGH
(see
https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_LOW)
No
Play any e-Skills game. Instead of a "right in your face" notification, you should see one if you open notifications drawer.
Tickets related to this pull-request: [ESKL-122](https://aptoide.atlassian.net/browse/ESKL-122)
**Questions:**
N/A

[task/ESKL-122] - Prevents spamming user with game notification

---

app/src/main/java/com/asfoundation/wallet/restore/intro/RestoreWalletModule.kt
app/src/main/java/com/asfoundation/wallet/restore/intro/RestoreWalletPresenter.kt
app/src/main/java/com/asfoundation/wallet/restore/password/RestoreWalletPasswordModule.kt
app/src/main/java/com/asfoundation/wallet/restore/password/RestoreWalletPasswordPresenter.kt

Fixes onboarding appearing again after recovering the wallet, when no password was set for the recover
No
Open onboarding and recover a wallet (both with  and without password), close the app, and launch It again
https://aptoide.atlassian.net/browse/APPC-2781

[APPC-2781] Fixed recover from onboarding

---

app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsViewModel.kt
app/src/main/java/com/asfoundation/wallet/ui/balance/BalanceInteractor.kt
app/src/main/java/com/asfoundation/wallet/wallets/repository/WalletInfoRepository.kt

Fixes an issue where wallet info error states would break Rx chains, which would then never recover in some cases (like 'My Wallets').
No
Turn off the network, and go to my wallets. It should display cached info about the wallet, and if the network is turned on and you go somewhere else (like Home) and come back, things should be updated / work as expected.
[APPC-2601](https://aptoide.atlassian.net/browse/APPC-2601)

[APPC-2601] Minor fix error states

---

app/build.gradle
billing/build.gradle
build.gradle
gamification/build.gradle
skills/build.gradle

This change make it possible to build and run project on the machines with Apple M1 CPU.
No
Check the main cases that involve working with DB and billing, gamification and skills modules.
Tickets related to this pull-request: [APPC-2928](https://aptoide.atlassian.net/browse/APPC-2928)

[APPC-2928] Make the project build and run on Apple M1 CPUs

---

app/src/main/java/com/asfoundation/wallet/navigator/NavigationExtensionsExt.kt

Fix the NFT Flow
This should be tested by going to the NFT page , then in the navigation bar click an icon that is not the my wallets one, and then come back to the my wallets and the page with the balance should display instead of the NFT one.
Tickets related to this pull-request: [APPC-2964](https://aptoide.atlassian.net/browse/APPC-2964)

Fix NFT Flow

---

app/src/main/java/com/asfoundation/wallet/backup/save_on_device/BackupSaveOnDeviceDialogFragment.kt
app/src/main/java/com/asfoundation/wallet/backup/save_on_device/BackupSaveOnDeviceDialogNavigator.kt
app/src/main/java/com/asfoundation/wallet/backup/save_on_device/BackupSaveOnDeviceDialogViewModel.kt
app/src/main/java/com/asfoundation/wallet/backup/save_options/BackupSaveOptionsFragment.kt
app/src/main/java/com/asfoundation/wallet/backup/save_options/BackupSaveOptionsNavigator.kt
app/src/main/java/com/asfoundation/wallet/backup/save_options/BackupSaveOptionsViewModel.kt
app/src/main/java/com/asfoundation/wallet/backup/skip/BackupSkipDialogFragment.kt
app/src/main/java/com/asfoundation/wallet/backup/skip/BackupSkipDialogNavigator.kt
app/src/main/java/com/asfoundation/wallet/backup/success/BackupSuccessFragment.kt
app/src/main/java/com/asfoundation/wallet/backup/triggers/BackupTriggerDialogFragment.kt
app/src/main/java/com/asfoundation/wallet/backup/triggers/BackupTriggerPreferences.kt
app/src/main/java/com/asfoundation/wallet/home/ui/HomeViewModel.kt
app/src/main/java/com/asfoundation/wallet/transactions/PerkBonusAndGamificationService.kt
app/src/main/res/layout/backup_trigger_dialog_fragment.xml

After changing wallets, the backup bottomsheet would work according to what happened to the previous wallet.
Added context when saving in the shared prefs with the wallet key, but in the future this might make more sense to simply change to a db.
Now the user can change wallets and the bottomsheet will appear when it should
No
- BackupTriggersPreferences.kt
- HomeViewModel.kt
- Recover a wallet that has a least one transaction
- Close the app and open to show the trigger
- dismiss the bottom sheet
- Change wallet to a new one (the trigger show not appear in all cases but another test is to see if it opens when the dismiss of the previous wallet was not done, it …

[bugfix/APPC-2782] Backup triggers fix

---

app/src/main/java/com/asfoundation/wallet/backup/success/BackupSuccessFragment.kt
app/src/main/java/com/asfoundation/wallet/backup/triggers/BackupTriggerDialogNavigator.kt
app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/PromoCodeBottomSheetViewModel.kt

Fixes the navigation from the backup triggers bottom sheet to the backup activity, since when a user completed a backup, returning to home would still have the bottom sheet because it wasn't dismissed.
Also fixes the bonus of the promocode not showing correctly when adding a promo code
- navigate to backup from the triggers (when returning, the bottom sheet wont be there, it will only be when the user opens the app again)
- complete the backup and check that even after closing, the bottom sheet wont appear anymore
https://aptoide.atlassian.net/browse/APPC-2782
https://aptoide.atlassian.net/browse/APPC-3045

[bugfix/APPC-2782] [bugfix/APPC-3045] Backup triggers and promo code bonus fix

---

app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogFragment.kt
app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
app/src/main/java/com/asfoundation/wallet/onboarding/bottom_sheet/TermsConditionsBottomSheetFragment.kt
app/src/main/java/com/asfoundation/wallet/onboarding/bottom_sheet/TermsConditionsBottomSheetViewModel.kt
app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/HasWalletUseCase.kt
app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/wallets/WalletsInteract.kt

Fix the onboarding navigation to avoid creating new wallet for the user that already has one.
No
Install the wallet app but do not perform the onboarding.
Buy a Gas item in the trivial drive (this vill create the wallet implicitly).
Open the wallet and perform the onboarding steps.
In the end no another one new wallet should be created.
Tickets related to this pull-request: [APPC-3047](https://aptoide.atlassian.net/browse/APPC-3047)

[APPC-3047] Z day 1st purchase

---

app/src/main/java/com/asfoundation/wallet/base/Navigator.kt
app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingNavigator.kt
app/src/main/res/navigation/onboarding_graph.xml

Prevents a user coming from the onboarding, to go back to it after entering home
When a user reaches home, pressing back should close the app
No
- Install the wallet, with all app data cleared
- go through the onboarding flow
- once the home appears, try to go back
https://aptoide.atlassian.net/browse/APPC-3122

[task/APPC-3122] Clear Onboarding backstack

---

app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordNavigator.kt
app/src/main/res/navigation/recover_wallet_graph.xml

related to https://github.com/Catappult/appcoins-wallet-android/pull/312
From the onboarding creating was working, but from the recover the user could still go back
Its a temporary solution to add flags like that, in the future with improvements in the multiple back stack from the navigation component, this should be changes
Yes | No
- Install the wallet, with all app data cleared
- go through the onboarding flow
- recover a wallet instead of creating one
- once the home appears, try to go back
https://aptoide.atlassian.net/browse/APPC-3122

[bugfix/APPC-3122] Clear backstack fix, from the recover screen

---

app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeRepository.kt
app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/GetUpdatedPromoCodeUseCase.kt
app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/ObservePromoCodeUseCase.kt
app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsPresenter.kt

promo codes that were already added, if they were renamed, the old ones became invalid and the would prevent the user from opening the bottom sheet
No
- add a promo code
- edit the database with database inspection to a random invalid string
- check that the code in the database changed and is now expired
- the user can remove or delete the current old code

[release/hotfix] fixes already added invalid promo codes

---

app/src/main/java/com/asfoundation/wallet/promo_code/PromoCodeResult.kt
app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetViewModel.kt
app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/ObservePromoCodeResultUseCase.kt
app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
app/src/main/java/com/asfoundation/wallet/redeem_gift/bottom_sheet/RedeemGiftBottomSheetFragment.kt

FIxes promo code error message, when a code as invalid the message was the wrong one.
Also fixes the extra space on the text inputs that would cause problems when verifying the code with the space.
This happened also in the redeem gift and the recover wallet text inputs
No
- Insert a invalid promo code, "Invalid code. Try with another one!” should appear instead of "Oops! This code couldn't be applied."
- Insert a valid code(megapack for example) but with extra spaces in the end, it should not give problems anymore
https://aptoide.atlassian.net/browse/APPC-3119

[bugfix/APPC-3119] Promo codes message fix

---

app/src/main/java/com/asfoundation/wallet/my_wallets/more/MoreDialogFragment.kt

Prevents the last wallet deletion, meaning that the Delete option will only appear if a user has 2 or more wallets
- Restore multiple wallets and check that the delete option will show with 2 or more
- Delete all wallets and check if the option disappears only in the last wallet
Tickets related to this pull-request: https://aptoide.atlassian.net/browse/APPC-3288

[bugfix/APPC-3288] Prevents the last wallet deletion

---

app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsFragment.kt

Prevents the disabled button layout to show when the button isn't ready, and just hides the button in that scenario.
- MyWalletFragment.kt 
- Inside the "More" dialog create a new wallet
- check the verify button during the wallet creation animation, it should be hidden.
https://aptoide.atlassian.net/browse/APPC-3289

[bugfix/APPC-3289] Verify card initial state

---

app/src/main/java/com/asfoundation/wallet/backup/repository/BackupRepository.kt
app/src/main/java/com/asfoundation/wallet/backup/use_cases/SendBackupToEmailUseCase.kt
app/src/main/java/com/asfoundation/wallet/ewt/EwtAuthenticatorService.kt
app/src/main/java/com/asfoundation/wallet/service/AccountWalletService.kt
bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/WalletService.kt
bdsbilling/src/test/java/com/appcoins/wallet/bdsbilling/BillingPaymentProofSubmissionTest.kt

Fixes the problem when a user has multiple wallets and tries to backup a non-active wallet.
- AccountWalletService.kt
- Create new wallets (2 or more)
- Backup the active wallet to check the flow
- Backup a non-active wallet via email
- Backup a non-active wallet via file
- Check if in both non-active cases, the backup was sucessful (check the file or text and try to recover)
- Check that the backend now was the backup information (wallet info endpoint) for that wallet
https://aptoide.atlassian.net/browse/APPC-3244

[bugfix/APPC-3244] Non-current wallet backup

---

app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt

Resolve the issue that payment conclusion events had value of 0.
Refactoring to stop using the parser in presenter performed. This conforms the way it is implemented for other fragments: to get the transaction builder from the bundle, not parsing it always from the string on each request. Also might unnoticeably slightly speed up payments with the credit card and PayPal
No

[APPC-3272] Value property for IAP in APPC-C

---

app/src/main/java/com/asfoundation/wallet/entity/WalletKeyStore.kt
app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordViewModel.kt
app/src/main/java/com/asfoundation/wallet/recover/result/RecoverEntryResult.kt
app/src/main/java/com/asfoundation/wallet/recover/result/RecoverPasswordResult.kt
app/src/main/java/com/asfoundation/wallet/recover/use_cases/RecoverPasswordKeystoreUseCase.kt
app/src/main/res/navigation/recover_wallet_graph.xml

It was only possible to have the name if the recover was not with password. This PR fixes the recover name when recovering a wallet that is protected by password. 
No
- RecoverPasswordVIewModel.kt
- Recover a wallet that is password protected with a file
- check if tha name of the file now is the name of the wallet
https://aptoide.atlassian.net/browse/APPC-3323

[bugfix/APPC-3323] Fix wallet name for password recover

---

app/src/main/java/com/asfoundation/wallet/app_start/FirstUtm.kt
app/src/main/java/com/asfoundation/wallet/app_start/Repositories.kt
app/src/test/java/com/asfoundation/wallet/app_start/FirstTopAppUseCaseTest.kt
app/src/test/java/com/asfoundation/wallet/app_start/FirstUtmUseCaseTest.kt

Add 5 seconds timeout in case if install referrer will never invoke a callback.
No
No reliable way to test.
Tickets related to this pull-request: [APPC-3335](https://aptoide.atlassian.net/browse/APPC-3335)

[APPC-3335] Add 5 seconds timeout on the install referrer retrieval

---

app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt

Notifications created in quick succession were not shown after a purchase is made. 
To test complete a purchase and check for the bonus notification
https://aptoide.atlassian.net/browse/APPC-3338

Fix concurrent notifications

---

app/src/main/AndroidManifest.xml

OOB 3ds flows (with authorization in the banking app) were not be able to be completed, due to the Adyen sdk not allowing the user to get back to the Adyen 3ds screen after authorizing the payment on the banking app.
Now the 3ds screen is kept open until the user goes back to the game.
AndroidManifest
To replicate the issue, do a payment with a CC with 3ds OOB.

3DS2 Activity on payment task

---

app/src/main/java/com/asfoundation/wallet/gamification/ObserveUserStatsUseCase.kt
app/src/main/java/com/asfoundation/wallet/main/splash/SplashExtenderViewModel.kt

Fixes the wallet getting stuck on the splash when there are no wallets created or recovered.
No
#418 
https://aptoide.atlassian.net/browse/APPC-3221

[bugfix/APPC-3221] Splash stuck on fresh install

---

app/src/main/java/com/asfoundation/wallet/service/AutoUpdateService.kt

fixes the update card notification not dismissing. 
it was not correctly saving a valid version to dismiss
No
- trigger the card with a higher version from the backend
- dismiss the card
https://aptoide.atlassian.net/browse/APPC-3379

[bugfix/APPC-3379] Update card dismiss

---

app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogFragment.kt
app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogNavigator.kt
app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordFragment.kt
app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordNavigator.kt
app/src/main/res/navigation/recover_wallet_graph.xml

Keeps the Success animation when not in the onboarding context, removes it in the onboarding
No
- Recover a wallet from the onboarding
- Recover a wallet from the my wallets or settings

Onboarding success animation

---

app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyView.kt

Allows the user to retry a payment with a different payment method if there was an error, instead of closing the payment flow.
No
On the credit card screen, turn-off the internet and try to proceed. Then click to go back.
https://aptoide.atlassian.net/browse/APPC-3404

[APPC-3404] Retry option on payment errors

---

app/src/main/java/com/asfoundation/wallet/service/GasService.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java

Deactivates unnecessary transaction/gas_price request from the payment flow. The endpoint is still used on "send" and NFTs.
No
Basic tests on payment flow.
https://aptoide.atlassian.net/browse/APPC-3387

[APPC-3387] Deactivate gas_price request on payments

---

app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentViewModel.kt
app/src/main/java/com/asfoundation/wallet/topup/TopUpActivityPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/WebViewActivity.kt
app/src/main/java/com/asfoundation/wallet/verification/ui/paypal/VerificationPaypalFragment.kt
app/src/main/java/com/asfoundation/wallet/verification/ui/paypal/VerificationPaypalViewModel.kt

Handle PayPal cancel action in webView Login into verify my Wallet
No
Have a wallet that is not verified, when trying to verify with PayPal, a button will appear that will have the option to cancel and return to Wallet, by clicking on this button you will be redirected to the wallet
Tickets related to this pull-request: [APPC-3425](https://aptoide.atlassian.net/browse/APPC-3425?atlOrigin=eyJpIjoiMTJjZDZlMTQzOWQ1NDc0MWE4ZGQzMTQ4MjU5ZGUyNjAiLCJwIjoiaiJ9)

[BugFix/APPC-3425] Handle PayPal cancel correctly

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/asfoundation/wallet/home/ui/HomeFragment.kt
app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt

Lineups necessary for Android 13:
- notifications permission and prompt,
- storage access logic to not depend on previous prompt
No
Check Recover Wallet.
Check notifications permission when opening the wallet.
https://aptoide.atlassian.net/browse/APPC-3617

[APPC-3617] Target Android 13

---

app/src/main/java/com/asfoundation/wallet/backup/BackupActivity.kt
app/src/main/java/com/asfoundation/wallet/backup/entry/BackupEntryFragment.kt
app/src/main/res/layout-land/backup_entry_fragment.xml

Fixes additional security toggle not opening in landscape 
Fixes crash when rotating the screen 
No
- Rotate the screen as many times as you want, to check if it crashes
- in landscape, try to toggle the additional seccurity 
https://aptoide.atlassian.net/browse/APPC-3656

[bugfix/APPC-3656] Backup flow landscape

---

app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultNavigator.kt

fixes screen rotation lock when finishing the first payment flow
No
- finish a payment in the new flow
- go to the home (explore wallet) and try to rotate the screen

Rotation lock after the first payment flow

---

app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsViewModel.kt

Fix a bug in some games when cached transaction has a value with 0 and currency to null, showing was error view to user.
No
set some value 0 and currency to null into a product to in DEV to get a response in this api - /transaction/inapp/cached_values
and with new apk not show error view .
Tickets related to this pull-request: [APPC-3717](https://aptoide.atlassian.net/browse/APPC-3717)

[APPC-3717] Bug in First Payment flow

---

app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationFragment.kt
ui/common/src/main/res/drawable/splash_background.xml
ui/common/src/main/res/values-ko/strings.xml
ui/common/src/main/res/values-tr/strings.xml

Fixed this problems - 
1- O logo da Wallet muda de cor quando o user é VIP no splashscreen.
2- Crash quando se carrega no "i" ao lado do bónus.
3 - no fim das active promos no ecrã das rewards, há um começo de um novo card que fica estranho. É quase um traço cinzento.
No
Click the button on gamification to see more information. And try the VIP wallet with logo changes Colors.
Tickets related to this pull-request: [APPC-3748](https://aptoide.atlassian.net/browse/APPC-3748)

[Feature/ APPC-3748] Fixed Bugs V2

---

app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
legacy/bdsbilling/src/test/java/com/appcoins/wallet/bdsbilling/BillingPaymentProofSubmissionTest.kt

1. Fix the support button not working in AdyenPaymentFragment.
2. Fix error strings not displaying in the pre-selected layout of the same class.
No
1. Force any error, for example a wrong date on a valid card.
2. Make a purchase with a credit card, then start another one but this time change the card so that the payment errors out.
https://aptoide.atlassian.net/browse/APPC-3812

[APPC-3812] Fix AdyenPaymentFragment error strings and support button

---

app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt

In the onboarding flow, when navigating from the Recover back to the onboarding fragment, the FragmentResultListener was lost.
No
Onboarding fragment -> already have a wallet -> back -> create wallet
https://aptoide.atlassian.net/browse/APPC-3849

[APPC-3849] Fix Onboarding create wallet not navigating

---

app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt

Eskills flow was crashing when user hadn't launched the wallet prior to a game. 
Skills activity calls are now only called after checking if wallet is created.
Yes | No
- Uninstall Wallet
- Install Wallet without opening it ( Make sure wallet creation flow doesn't start)
- Open eSkills game and try to make a purchase
- You should see the wallet creation flow, prior to the payment fragment.
Tickets related to this pull-request: [ESKL-365](https://aptoide.atlassian.net/browse/ESKL-365)
[ESKL-365]: https://aptoide.atlassian.net/browse/ESKL-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

Adds wallet creation flow to eskills activity calls

---

core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/CreditsPurchaseBody.kt
legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt

Adds oemid to eskills purchases body.
Yes | No
- Ask for a game with an injected oemId (easier in release version)
- Try making an eskills purchase
- Your purchase should be visible in the oem_id wallet: https://appcexplorer.io/search/0xd9e72e7cf52747d52fd6eacb62bbe3e41395517c
Tickets related to this pull-request: [APPC-3708(https://aptoide.atlassian.net/browse/APPC-3708)

[APPC-3708] Adds oemid to CreditsPurchaseBody

---

app/src/main/res/layout/payment_methods_layout.xml

When a payment method was preselected and the bonus was showing, the "other payment methods" button was hidden behind the bonus
No
https://aptoide.atlassian.net/browse/APPC-3939

[APPC-3939] Fix overlapping button on pre-selected payment method screen

---

app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt
app/src/main/res/navigation/recover_wallet_graph.xml

Fix bug where bottom navigation is not appearing when comes from Recover
No
try to recover a wallet from onboarding, bottom navigation should appears at home
Tickets related to this pull-request: [APPC-3930](https://aptoide.atlassian.net/browse/APPC-3930)
[APPC-3930]: https://aptoide.atlassian.net/browse/APPC-3930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APCC-3930][Fix] Change navigation from recover to NavBar instead to home_graph

---

app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
app/src/main/java/com/asfoundation/wallet/wallet/home/HomeNavigator.kt
app/src/main/java/com/asfoundation/wallet/wallet/home/HomeViewModel.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceCardComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceCardExpandedComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/component/Amount.kt

Change the click action of the arrow next to balance to show a bottomsheet with all balances and add this same action when user clicks on balance.
No
Go to home and click on balance and the arrow next to the balance, it should show a bottomsheet  with all balances.
Tickets related to this pull-request: [APPC-3982](https://aptoide.atlassian.net/browse/APPC-3982)
[APPC-3982]: https://aptoide.atlassian.net/browse/APPC-3982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-3982] Show BalanceBottomSheet on Home balance click

---

legacy/skills/src/main/java/cm/aptoide/skills/games/BackgroundGameService.kt

Following tests in Android 14, the forgroundService issue persisted in some situations. 
This PR fixes the issue where in a worst case scenario, the service is aborted without error
No
Play a match with Android 14 device
Tickets related to this pull-request: [ESKL-383](https://aptoide.atlassian.net/browse/ESKL-383)
[ESKL-383]: https://aptoide.atlassian.net/browse/ESKL-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ESKL-383): add version check and specific foregroundStart

---

app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt

Fixed redirect into recovery wallet to homeFragment for prevent hidden bottom navigation
No
Try recovery wallet on onbarding and inside wallet.
Tickets related to this pull-request: [APPC-4086](https://aptoide.atlassian.net/browse/APPC-4086)
[APPC-4086]: https://aptoide.atlassian.net/browse/APPC-4086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix[APPC 4086] bottom navigation hidden or smashed

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/asfoundation/wallet/analytics/IndicativeInitializeWrapper.kt
app/src/main/java/com/asfoundation/wallet/analytics/InitilizeDataAnalytics.kt
core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/AnalyticsLabels.kt
core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeAnalytics.kt
core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/InstallerService.kt
core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/InstallerSourceService.kt
core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/PartnerAddressService.kt
core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OemIdPreferencesDataSource.kt

include super properties inside Analytics to send in every analytics if user have GH installed and correct OEMID
No
Clean the wallet cache and open wallet with GH install or not and see the analytics parameter gh_oemid
Tickets related to this pull-request: [APPC-4095](https://aptoide.atlassian.net/browse/APPC-4095)
[APPC-4095]: https://aptoide.atlassian.net/browse/APPC-4095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat[APPC-4095]  Analytics Identify if users have GamesHub installed

---

app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
app/src/main/java/com/asfoundation/wallet/wallet/home/HomeViewModel.kt
app/src/main/java/com/asfoundation/wallet/wallet_reward/GamificationHeaderModel.kt
app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardViewModel.kt
feature/challenge-reward/data/src/main/java/com/appcoins/wallet/feature/challengereward/data/presentation/ChallengeRewardVisibilityViewModel.kt
feature/challenge-reward/data/src/main/java/com/appcoins/wallet/feature/challengereward/data/presentation/ViewModelProvider.kt
ui/common/src/main/java/com/appcoins/wallet/ui/common/theme/WalletColors.kt
ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceCardComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceCardExpandedComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsActionsComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsGamificationComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/ShimmerSkeletonComposable.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/TransactionsComposable.kt

Add Skeleton Loading for Home and Rewards Fragments to show a loading
No
Open Home and Rewards with bad connection
Tickets related to this pull-request: [APPC-3869](https://aptoide.atlassian.net/browse/APPC-3869)
[APPC-3869]: https://aptoide.atlassian.net/browse/APPC-3869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-3869] Skeleton Loading for Home and Rewards

---

app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAdapter.kt

When in Russia (VPN), no one payment method is preselected
No
Change VPN to Russia and make a payment, it should have the first payment method selected
Tickets related to this pull-request: [APPC-4076](https://aptoide.atlassian.net/browse/APPC-4076)
[APPC-4076]: https://aptoide.atlassian.net/browse/APPC-4076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4076] Fix preselection of payment methods in Russia

---

core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/BrokerBdsApi.kt
legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt

Add Header on /methods api to return payment methods with selected language
No
try to make a payment and verify if the language of the payment methods is the same of the device, doesn’t try it with english, because it is the default.
Tickets related to this pull-request: [APPC-4009](https://aptoide.atlassian.net/browse/APPC-4009)
[APPC-4009]: https://aptoide.atlassian.net/browse/APPC-4009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4009]Add language to payment methods api

---

ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsActionsComposable.kt

set dynamically the height of the action cards on rewards screen
No
go to rewards screen and check if cards height is correct
Tickets related to this pull-request: [APPC-4091](https://aptoide.atlassian.net/browse/APPC-4091)
[APPC-4091]: https://aptoide.atlassian.net/browse/APPC-4091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4091] Fix height bug on ActionCard Composable

---

app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt

Fix first payment analytics after recover from web to log regular.
No
after recover a wallet from first payment in web, verify indicative to validate if regular is on tags
Tickets related to this pull-request: [APPC-4304](https://aptoide.atlassian.net/browse/APPC-4304)
[APPC-4304]: https://aptoide.atlassian.net/browse/APPC-4304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4304]HotFix first payment analytics after recover from web

---

app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt

On VK Pay, navigates back to payment methods screen if the user closes the bottom sheet.
No
Try closing both vk id and vk pay
https://aptoide.atlassian.net/browse/APPC-4200

[APPC-4200] VK back navigation

---

app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/code/VerificationCodePresenter.kt
app/src/main/res/layout/fragment_verification_code.xml

This PR fix a overlapping of screens on verification with credit card, as described on Jira.
No
Start the verify flow, insert the valid dev card, turn off the wifi on the insert code screen, insert a wrong code, then tap on continue, on this step should appear no network error instead of the old problem.
Tickets related to this pull-request: [APPC-2428](https://aptoide.atlassian.net/browse/APPC-2428)
[APPC-2428]: https://aptoide.atlassian.net/browse/APPC-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Hotfix][APPC-2428] Fix overlapping error screens on verify

---

app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt

This PR changes the Iap paypal logout button from dark mode to light mode.
No
Make a payment with paypal to have the pre-selected paypal. On the paypal screen, select the paypal menu button to show the logout button. check if its in light mode instead of dark mode.
Tickets related to this pull-request: [APPC-4169](https://aptoide.atlassian.net/browse/APPC-4169)
[APPC-4169]: https://aptoide.atlassian.net/browse/APPC-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4169] Iap paypal logout button in dark mode

---

app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
app/src/main/res/layout-land/fragment_top_up.xml
app/src/main/res/layout/fragment_top_up.xml

Fixes the empty space for bonuses that don't have bonuses.
No
Go to TopUp screen and check if the bonuses disappear or not depending if the payment method has bonuses or not.
Tickets related to this pull-request: [APPC-4173](https://aptoide.atlassian.net/browse/APPC-4173)
[APPC-4173]: https://aptoide.atlassian.net/browse/APPC-4173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4173] Top up space for bonus is empty in payment methods that don't give bonuses

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/asfoundation/wallet/main/MainActivity.kt
app/src/main/java/com/asfoundation/wallet/main/MainActivityNavigator.kt
app/src/main/java/com/asfoundation/wallet/main/MainActivityViewModel.kt
app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragment.kt
app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragmentNavigator.kt
app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetViewModel.kt
app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardNavigator.kt
app/src/main/res/navigation/main_graph.xml
app/src/main/res/navigation/reward_graph.xml
convention/src/main/java/com/appcoins/wallet/convention/plugins/AndroidAppPlugin.kt

This PR opens the promocode bottom sheet and adds the promocode automatically to the text field.
No
Open the app to validate that it opens normally.
Also use a deeplink to open the app. This can be done using the following prompt command:
`adb shell am start -W -a android.intent.action.VIEW -d "appcoins://promocode?promocode=12345"`
Tickets related to this pull-request: [APPC-4445](https://aptoide.atlassian.net/browse/APPC-4445)
[APPC-4445]: https://aptoide.atlassian.net/browse/APPC-4445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4445] Add navigation to promoCode screen from deeplink

---

app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/WalletsAddressProvider.kt
app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
app/src/main/res/layout/settings_promo_code_bottom_sheet_layout.xml
core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/PromoCodeBonusResponse.kt
feature/promo-code/data/src/main/java/com/appcoins/wallet/feature/promocode/data/PromoCodeResult.kt
feature/promo-code/data/src/main/java/com/appcoins/wallet/feature/promocode/data/error/UserOwnPromoCode.kt
feature/promo-code/data/src/main/java/com/appcoins/wallet/feature/promocode/data/repository/PromoCode.kt
feature/promo-code/data/src/main/java/com/appcoins/wallet/feature/promocode/data/repository/PromoCodeRepository.kt
feature/promo-code/data/src/main/java/com/appcoins/wallet/feature/promocode/data/wallet/WalletAddress.kt
ui/common/src/main/res/values/styles_views.xml
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WalletTextFieldView.kt

Added logic to show error when user wants to add his own promo code. Also created a new type for the WalletTextFieldView to accept a regex for the input and also to have the text all caps.
No
Go to the promo code bottom sheet. Try do add special characters and non-caps letters. Validate that you can only add numbers and capitalized letters.
Try to add your own promo code. Validate the error message and that the promo code is not used.
Tickets related to this pull-request: [APPC-4472](https://aptoide.atlassian.net/browse/APPC-4472)
[APPC-4472]: https://aptoide.atlassian.net/browse/APPC-4472?atlOrigin=eyJpIjo …

[APPC-4472] Vip promo codes not allow to add their own promo code

---

app/src/main/res/layout/home_manage_wallet_bottom_sheet_layout.xml

This screen had an issue that after opening settings screen, and the open the Manage Wallet bottom sheet, the "t's" on the end of "wallet" words would be obfuscated on the starting of the screen.
Fixed this issue.
No
Open settings screen. After that open the manage wallet bottom sheet.
Tickets related to this pull-request: [APPC-4493](https://aptoide.atlassian.net/browse/APPC-4493)
[APPC-4493]: https://aptoide.atlassian.net/browse/APPC-4493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC 4493] Cursor on bottom sheet text

---

app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
app/src/main/java/com/asfoundation/wallet/billing/googlepay/GooglePayWebFragment.kt
app/src/main/java/com/asfoundation/wallet/di/RxSchedulers.kt
app/src/main/java/com/asfoundation/wallet/onboarding/pending_payment/OnboardingPaymentViewModel.kt
app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/OnboardingPaymentEvents.kt
app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/EarnAppcoinsFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/MergedAppcoinsFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeeFragment.kt
app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/status/CarrierPaymentFragment.kt
app/src/main/java/com/asfoundation/wallet/util/IntentExtensions.kt
app/src/main/res/layout-land/fragment_top_up.xml
app/src/main/res/layout/fragment_top_up.xml
core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/EventSender.kt

This PR has some code refactored for easier reading. It also adds the oemId to the wallet_payment_start analytic.
No
Tickets related to this pull-request: [APPC-4494](https://aptoide.atlassian.net/browse/APPC-4494)
[APPC-4494]: https://aptoide.atlassian.net/browse/APPC-4494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4494] Payment start add property oemId

---

app/src/main/java/com/asfoundation/wallet/app_start/AppStart.kt
app/src/main/java/com/asfoundation/wallet/app_start/Probes.kt
app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/RestoreGuestWalletFlowUseCase.kt

Changed RestoreGuestWalletUseCase  to send extra parameters when exists cachedTransaction (integrationFlow, sku,packageName)
Fixed bug to enter on RestoreGuestWalletUseCase when it's not right
No
Try  to make a first purchase and see into logs values ​​that are sent to analytics
Tickets related to this pull-request: [APPC-4560](https://aptoide.atlassian.net/browse/APPC-4560)
[APPC-4560]: https://aptoide.atlassian.net/browse/APPC-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4560] Wallet_first_launch missing fields

---

app/src/main/java/com/asfoundation/wallet/home/HomeFragment.kt
ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt

Fix misplaced "Get" button on promotions card
No
Check home screen and see the promotions card. "Get" button should be right aligned.
Tickets related to this pull-request: [APPC-4001](https://aptoide.atlassian.net/browse/APPC-4001)
[APPC-4001]: https://aptoide.atlassian.net/browse/APPC-4001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4001] Promotions get buttons are not visible

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt

Adds autofill to webview during IAP and topup
No
Open the Paypal webview for payment. check if the login credentials are stored.
Tickets related to this pull-request: [APPC-4539](https://aptoide.atlassian.net/browse/APPC-4539)
[APPC-4539]: https://aptoide.atlassian.net/browse/APPC-4539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4539] Paypal custom tabs use password manager

---

app/src/main/java/com/asfoundation/wallet/main/MainActivity.kt
app/src/main/java/com/asfoundation/wallet/main/MainActivityNavigator.kt
app/src/main/java/com/asfoundation/wallet/main/MainActivityViewModel.kt
app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragment.kt
app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragmentNavigator.kt
app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogFragment.kt
app/src/main/java/com/asfoundation/wallet/onboarding/BackupModel.kt
app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
app/src/main/java/com/asfoundation/wallet/onboarding/pending_payment/OnboardingPaymentFragment.kt
app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt
app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
app/src/main/res/navigation/main_graph.xml
app/src/main/res/navigation/onboarding_graph.xml
core/utils/android-common/src/main/java/com/appcoins/wallet/core/utils/android_common/AppUtils.kt
core/utils/android-common/src/main/java/com/appcoins/wallet/core/utils/android_common/OnNewIntentActivityHandler.kt

There was an issue when the app was launched from a promocode or giftcard and there was no wallet created. In this scenario the promocode/giftcard screens were not showing up with the data. Fix this issue by recovering the intent on restart. The onboarding is not recovering the intent because if the onboarding is appearing, its because the app was not started from a promocode/giftcard deeplink
No
Launch the app using a deeplink with a promocode or giftcard. validate that the promocode or giftcard screens appear.
Tickets related to this pull-request: [APPC-4669](https://aptoide.atlassian.net/browse/APPC-4669)
**Code Review …

[APPC-4669] Promo code deeplink error if no wallet created

---

ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt

Changes the texts sizes on the promotion cards to avoid cropping in these texts.
No
Check the promotions cards on home screen or in rewards screen and validate that the time texts are not cropped.
Tickets related to this pull-request: [APPC-4695](https://aptoide.atlassian.net/browse/APPC-4695)
[APPC-4695]: https://aptoide.atlassian.net/browse/APPC-4695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4695] Promotions cropped counter

---

core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/AdyenApi.kt
core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/FraudResult.kt
legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapper.kt
legacy/billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapperTest.kt

Adjusts fraud object validation and bumps the api version
No
Try a payment with fraud. Validate that it appears the fraud screen and also the success is working correctly.
Tickets related to this pull-request: [APPC-4706](https://aptoide.atlassian.net/browse/APPC-4706)
[APPC-4706]: https://aptoide.atlassian.net/browse/APPC-4706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPC-4706] Adyen sdk update adjust fraud object validation
