- app/src/main/java/com/asfoundation/wallet/billing/analytics/BillingAnalytics.java
- app/src/main/java/com/asfoundation/wallet/billing/analytics/EventSender.java
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeeFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeeModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeePresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeeView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/status/CarrierPaymentModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyView.kt
- app/src/main/java/com/asfoundation/wallet/util/ExtensionFunctionUtils.kt
Fixes an issue where carrier billing was not working when the wallet was not eligible for bonus credits. Also fixes an issue with analytics and a different issue where if you changed wallets (from one with bonus to one without), it wouldn't remove the bonus when proceeding with a payment.
No
- Check carrier billing on a wallet without bonus. It should work as expected
- Analytics should now send the one specified by Ana for the phone number screen.
- Go to PaymentMethods screen with a wallet with bonus. Without closing, switch to a wallet without bonus. When coming back and choosing a payment (like Carrier Billing), it should update accordingly and not display the bonus.
**What are the relevant …
> [WAL-57] Carrier Billing - No Bonus bug

- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyPresenter.kt
Fixes a bug where eternal loading would occur if webservices returned an unknown fee. Now it goes to an error screen.
No
Force the 'paymentModel.carrier' or fee cost to be null and check that it logs the error and navigates to the error screen. The normal flow should still work too.
[WAL-57](https://aptoide.atlassian.net/browse/WAL-57)
> [WAL-57] Unknown fee bug

- app/src/main/res/layout/fragment_carrier_confirm.xml
Fixes issue with scaling of carrier image.
Check that the carrier image in the carrier billing flow looks ok.
[WAL-57](https://aptoide.atlassian.net/browse/WAL-57)
> [WAL-57] Scale type bug

- app/src/main/res/layout-land/fragment_carrier_confirm.xml
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/CarrierBillingRepository.kt
Fixes issue with scaling of carrier image on landscape and fixes return URL.
Check that the carrier image in the carrier billing flow looks ok and that the sucess flow works correctly.
[WAL-57](https://aptoide.atlassian.net/browse/WAL-57)
> WAL-57 - Issue with return URL and image size

- app/build.gradle
- billing/build.gradle
- build.gradle
Update version for proxy sdk to version that is now updated for the new domain on catappult.io for dev environment
> Update AppCoins SDK

- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeeFragment.kt
Fix fee copy for carrier billing
Flow on how to test this or QA Tickets related to this use-case: [WAL-57](https://aptoide.atlassian.net/browse/WAL-57)
Tickets related to this pull-request: [WAL-57](https://aptoide.atlassian.net/browse/WAL-57)
> [WAL-57] Fix wrong replacement on string after copy update

- app/src/main/java/com/asfoundation/wallet/analytics/AmplitudeAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/analytics/AnalyticsSetup.kt
- app/src/main/java/com/asfoundation/wallet/analytics/RakamAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/analytics/RakamEventLogger.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/di/InteractorModule.kt
- app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
Add superproperty for type of users.
No
1 - Open the wallet
2 - Go to rakam and export the csv data:
goto https://app.rakam.io/10175/explore/sql/?id=13686
change package to com.appcoins.wallet.dev
change _user to the wallet you're using.
3 - You should see in the first column  ""wallet_origin"": ""UNKNOWN"" (or any other origin your wallet comes from)
Tickets related to this pull-request: [WAL-138](https://aptoide.atlassian.net/browse/WAL-138)
**Questions:**
> [WAL-138] - Added rakam superproperty for type of users.

- app/src/main/java/com/asfoundation/wallet/di/RepositoryModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/AvailableCountryListViewModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/CarrierInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyView.kt
- app/src/main/res/layout-land/fragment_carrier_verify_phone.xml
- app/src/main/res/layout/fragment_carrier_verify_phone.xml
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/AvailableCountryListModel.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/CarrierBillingRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/CarrierResponseMapper.kt
Added filter to phone country list to be based on the available carrier billing country list
No
CarrierBillingVerifyPresenter.kt
Use VPN for France and check if the list only shows France as the country of available phone number
https://aptoide.atlassian.net/browse/WAL-122
> [WAL-122] Dimoco - Reduce phone list

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/purchase/InAppDeepLinkRepository.kt
- app/src/main/java/com/asfoundation/wallet/billing/purchase/LocalPaymentsLinkRepository.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentData.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/CarrierInteractor.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/CarrierBillingRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/request/CarrierTransactionBody.kt
Added changes required to send the referrer url to the carrier billing and adyen payments
Flow on how to test this or QA Tickets related to this use-case: [MOB-XXXX](https://aptoide.atlassian.net/browse/WAL-157)
Tickets related to this pull-request: [MOB-XXXX](https://aptoide.atlassian.net/browse/WAL-157)
**Questions:**
> [WAL-157] Add referrer url on payment flows where it is missing

- build.gradle
Update okhttp version so that http performs automatic redirects whenever backend sends 307 HTTP code (Temporary Redirect).
Previous version (4.4.1), only allowed for automatic redirects in GETs and HEADs ([RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.8)) Now, since [4.6.0](https://square.github.io/okhttp/changelog/#version-460), it can be for GETs, POSTs, PUTs, all types, can be redirected by the okhttp client automatically ([RFC-7231](https://tools.ietf.org/html/rfc7231#section-6.4.7)).
No
- Project's build.gradle
You can't really test this as-is, since to my knowledge there are no active redirects from api side being used by wallet. …
> [APPC-2172] Handle api redirect

- app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
title
No
PromotionsInteractor.kt
> [hotfix] Fixed promotions screen when there are perks, but no gamification

- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/CarrierInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/common/model/WalletAddresses.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/CarrierBillingRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/request/CarrierTransactionBody.kt
Added missing field for a purchase with carrier billing (metadata and callback_url).
Flow on how to test this or QA Tickets related to this use-case: [MOB-XXXX](https://aptoide.atlassian.net/browse/APPC-2254)
Tickets related to this pull-request: [MOB-XXXX](https://aptoide.atlassian.net/browse/APPC-2254)
> APPC-2254 - Add missing fields

- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/CarrierInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/status/CarrierPaymentPresenter.kt
> [hotfix] Fixed non-ending loading

- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Add missing field on local payment transaction creation on calls to the broker service
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [APPC-2258](https://aptoide.atlassian.net/browse/APPC-2258)
Tickets related to this pull-request: [APPC-2258](https://aptoide.atlassian.net/browse/APPC-2258)
**Questions:**
> [APPC-2258] Add missing field on local payments purchase flow

- app/src/main/java/com/asfoundation/wallet/di/InteractorModule.kt
- app/src/main/java/com/asfoundation/wallet/repository/AllowanceService.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/ApproveKeyProvider.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/AsfInAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/BdsInAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyInteract.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/test/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractorTest.java
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BdsBilling.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/Billing.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingPaymentProofSubmissionImpl.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingRepository.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/TransactionType.kt
Adds the check for current transactions on OSP.
Currently we are only doing it for normal inapp.
No
PaymentMethodsPresenter.kt
Try to do a purchase (buy oil) with APPC and leave in the middle of the purchase, then try to start another buy oil purchase and check if the transaction resume successfully
https://aptoide.atlassian.net/browse/APPC-2237
> [APPC-2237] Added check for unmanaged sku processing transactions

- app/src/main/res/layout/item_top_value.xml
Added margins to default topup values to increase readability
No
Check if the values are more readable when in Indonesia and check if the values in PT for example still look the same
https://aptoide.atlassian.net/browse/APPC-2230
> [APPC-2230] Added margin to default topup values

- app/src/main/java/com/asfoundation/wallet/verification/code/VerificationCodePresenter.kt
Fixed Verify 2.0 success screen 
No
Alter the code so it shows success on the error case. Check if what happens in the video of the comments of the ticket no longer happens. Also, check if the error case also displays correctly.
https://aptoide.atlassian.net/browse/APPC-2194
**Questions:**
> [APPC-2194] Fixed Verify 2.0 success screen

- app/src/main/java/com/asfoundation/wallet/di/InteractorModule.kt
- app/src/main/java/com/asfoundation/wallet/di/RepositoryModule.kt
- app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/vouchers/MockedVouchersRepository.kt
- app/src/main/java/com/asfoundation/wallet/vouchers/VouchersRepository.kt
- app/src/test/java/com/asfoundation/wallet/promotions/PromotionsInteractorTest.kt
- app/src/test/java/com/asfoundation/wallet/promotions/PromotionsRepositoryTest.kt
- gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
Adds unit tests to promotions interactor and repository
Yes | No
**Questions:**
> [APPC-2239] E-Vouchers promotions screen unit tests

- app/src/main/java/com/asfoundation/wallet/billing/analytics/BillingAnalytics.java
Yes | No
Check if event appears in rakam (can only be tested in Prod)
https://aptoide.atlassian.net/browse/MOB-2308
> [APPC-2308] Changed name of field for error risk rules

- app/src/main/java/com/asfoundation/wallet/restore/password/RestoreWalletPasswordFragment.kt
Check ticket description
No
RestoreWalletFragment.kt
https://aptoide.atlassian.net/browse/APPC-2320
https://aptoide.atlassian.net/browse/APPC-2320
**Questions:**
> [APPC-2320] Change text of color back to black after error on restore

- app/src/main/java/com/asfoundation/wallet/subscriptions/SubscriptionModel.kt
- app/src/main/java/com/asfoundation/wallet/subscriptions/UserSubscriptionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/subscriptions/list/SubscriptionListPresenter.kt
Adds empty screen animation when there are only pending subs. At the moment it's showing a blank screen
No
Make a sub in Pello app and check if it is Pending and check if it shows an empty screen with the animation
https://aptoide.atlassian.net/browse/APPC-2335
> [APPC-2335] Fixed empty screen when there are only pending subs

- app/src/main/java/com/asfoundation/wallet/di/RepositoryModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyView.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/AvailableCountryListModel.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/CarrierBillingRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/CarrierResponseMapper.kt
- billing/src/main/java/com/appcoins/wallet/billing/carrierbilling/response/CountryListResponse.kt
Implements API to set the default country when entering carrier billing based on IP.
No
Use VPN for a valid carrier billing country (e.g. Italy, France) and check that it has the corresponding country set by default. You can also check if everything works as expected.
[APPC-2259](https://aptoide.atlassian.net/browse/APPC-2259)
> [bugfix/APPC-2259] Default Country for Carrier Billing

- app/src/main/java/com/asfoundation/wallet/analytics/TaskTimer.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
This PR measures the time to load payment methods (and different chains inside it) and sends this info as analytics to Rakam.
No
Check if the expected events are being sent to Rakam (you can check with logcat).
[APPC-2403](https://aptoide.atlassian.net/browse/APPC-2403)
> [task/APPC-2403] Measure time to load Payment Methods

- skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
- skills/src/main/java/cm/aptoide/skills/util/DeviceScreenManager.kt
- Prevents screen lock when user is waiting in queue
NOTE: jenkins job will fail. see #105 for fix
No
Open 2048 and purchase, wait for opponent to join in, your screen should not lock or dim.
Tickets related to this pull-request: [ESKL-5](https://aptoide.atlassian.net/browse/ESKL-5)
**Questions:**
N/A
> [ESKL-5/screen-lock] - Prevents screen lock when user is waiting in queue

- skills/src/main/java/cm/aptoide/skills/repository/TicketRepository.kt
- skills/src/main/java/cm/aptoide/skills/usecase/CreateTicketUseCase.kt
- skills/src/main/java/cm/aptoide/skills/util/EskillsUri.kt
- Receives roomMetadata from URI, parses and sends to backend on createTicket request
No
With 2048 from `metadata` branch, try to create a ticket (start a game) with and without metadata on URI. Check with Charles if this field is sent correctly to the backend.
Tickets related to this pull-request: [ESKL-7](https://aptoide.atlassian.net/browse/ESKL-7)
**Questions:**
N/A
> [eskl-7/metadata] - Receives roomMetadata from URI

- skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
- skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt
- skills/src/main/java/cm/aptoide/skills/entity/UserData.kt
- skills/src/main/java/cm/aptoide/skills/model/TicketStatus.kt
- skills/src/main/res/layout/fragment_skills.xml
- skills/src/main/res/layout/refund_ticket_layout.xml
- skills/src/main/res/values/strings.xml
> [ESKL-11] - Added support to refunded ticket.

- app/src/main/java/com/asfoundation/wallet/skills/SkillsModule.kt
- skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
- skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt
- skills/src/main/java/cm/aptoide/skills/api/TicketApi.kt
- skills/src/main/java/cm/aptoide/skills/model/TicketRequest.kt
- skills/src/main/java/cm/aptoide/skills/repository/TicketRepository.kt
- skills/src/main/java/cm/aptoide/skills/usecase/CancelTicketUseCase.kt
- skills/src/main/java/cm/aptoide/skills/usecase/CreateTicketUseCase.kt
- skills/src/main/java/cm/aptoide/skills/util/EskillsParameters.kt
- skills/src/main/java/cm/aptoide/skills/util/EskillsUri.kt
- skills/src/main/res/layout/loading_ticket_layout.xml
- skills/src/main/res/values/strings.xml
Adds a cancel button on loading dialog that refunds ticket if the user
has already payed, otherwise only returns to maingame
No
**Questions:**
> [ESKL-9/cancel-button] - Cancel button to refund ticket

- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/transactions/TransactionsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/TransactionsActivity.java
- app/src/main/java/com/asfoundation/wallet/viewmodel/TransactionsViewModel.java
Implements analytics for the new home.
Note: Home refactor must be accepted before this, and also there's still events still to define.
No
Check if all defined analytics are correctly being sent.
[APPC-2426](https://aptoide.atlassian.net/browse/APPC-2426)
> [feature/APPC-2426] New Home Analytics

- app/schemas/com.asfoundation.wallet.repository.TransactionsDatabase/5.json
- app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
- app/src/main/java/com/asfoundation/wallet/entity/WalletHistory.java
- app/src/main/java/com/asfoundation/wallet/repository/TransactionMapper.kt
- app/src/main/java/com/asfoundation/wallet/repository/TransactionsDatabase.kt
- app/src/main/java/com/asfoundation/wallet/repository/entity/TransactionEntity.kt
- app/src/main/java/com/asfoundation/wallet/transactions/Transaction.java
- app/src/main/java/com/asfoundation/wallet/transactions/TransactionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/ui/widget/holder/TransactionHolder.java
- app/src/main/java/com/asfoundation/wallet/util/CurrencyFormatUtils.kt
- app/src/main/res/layout/item_transaction.xml
- app/src/test/java/com/asfoundation/wallet/transactions/TransactionsMapperTest.kt
Implements fiat on transactions that are Top-ups or IAP off-chain that are paid with fiat.
Also removes transaction status string
Yes
- TransactionHolder.java
- WalletHistory.java
- TransactionEntity.java
Check top up or iap off-chain transactions in home screen and check if it matches the requirements
https://aptoide.atlassian.net/browse/APPC-2283
> [feature/APPC-2283] Show fiat on transactions

- app/src/main/java/com/asfoundation/wallet/billing/analytics/WalletsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/billing/analytics/WalletsEventSender.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/balance/BalanceFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/balance/BalanceFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/balance/BalanceFragmentView.kt
- app/src/main/java/com/asfoundation/wallet/ui/wallets/WalletsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/wallets/WalletsPresenter.kt
Adds analytics for "My wallets" screen to report usage.
No
Check if every event is being sent correctly as specified.
[APPC-2443](https://aptoide.atlassian.net/browse/APPC-2443)
> [feature/APPC-2443] My wallets usage analytics

- app/src/main/java/com/asfoundation/wallet/C.java
- app/src/main/java/com/asfoundation/wallet/di/TransactionDetailModule.kt
- app/src/main/java/com/asfoundation/wallet/entity/GlobalBalance.kt
- app/src/main/java/com/asfoundation/wallet/entity/TransactionsDetailsModel.kt
- app/src/main/java/com/asfoundation/wallet/navigator/TransactionViewNavigator.kt
- app/src/main/java/com/asfoundation/wallet/router/TransactionDetailRouter.kt
- app/src/main/java/com/asfoundation/wallet/service/currencies/LocalCurrencyConversionService.kt
- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
- app/src/main/java/com/asfoundation/wallet/viewmodel/TransactionDetailViewModel.java
- app/src/main/java/com/asfoundation/wallet/viewmodel/TransactionDetailViewModelFactory.java
- app/src/main/java/com/asfoundation/wallet/viewmodel/TransactionsViewModel.java
- app/src/main/res/layout/activity_transaction_detail.xml
Shows fiat on transaction details, both paid fiat information and converted fiat information when the currency from the global balance is different from the currency paid on the transaction. Also changes done in the layout to replicate the design.
No
- TransactionDetailActivity.java
- TransactionDetailViewModel.java
- LocalCurrencyConversionService.kt 
open a transaction without fiat values and check value
open a transaction with fiat and check values.
open a transaction paid with a different currency from the balance currency
https://aptoide.atlassian.net/browse/APPC-2283
> [feature/APPC-2283] Show fiat on transactions details

- app/src/main/java/com/asfoundation/wallet/service/currencies/LocalCurrencyConversionService.kt
fixes the wrong order in the conversion request 
No
- LocalCurrencyConversionService.kt
https://aptoide.atlassian.net/browse/APPC-2283
> [APPC-2465] conversion request fix

- app/src/main/java/com/asfoundation/wallet/service/currencies/RoomCurrencyConversionRatesPersistence.kt
Small fix to infinite balance skeleton in home screen, error was caused by division by zero.
No
- RoomCurrencyConversionRatesPersistence.kt
- Open app and check the balance skeleton
- Test the create wallet flow
https://aptoide.atlassian.net/browse/APPC-2550
> [bugfix/APPC-2550] Infinite Balance skeleton fix

- app/src/main/java/com/asfoundation/wallet/MainActivity.kt
- app/src/main/java/com/asfoundation/wallet/analytics/AmplitudeAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/analytics/AnalyticsSetup.kt
- app/src/main/java/com/asfoundation/wallet/analytics/RakamAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsModel.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/PromotionsFragment.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/PromotionsNavigator.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/PromotionsViewModel.kt
Minor revision according to the comments in https://github.com/Catappult/appcoins-wallet-android/pull/124.
No
Simply check if no behavior has changed since https://github.com/Catappult/appcoins-wallet-android/pull/124, other than the intended fixes (like not handling Aptoide redirects).
[APPC-2466](https://aptoide.atlassian.net/browse/APPC-2466)
> [bugfix/APPC-2466] BN Promotions - Minor revision

- app/src/main/java/com/asfoundation/wallet/util/UserAgentInterceptor.kt
Updated user-agent to include android id
No
Flow on how to test this or QA Tickets related to this use-case: [APPC-2503](https://aptoide.atlassian.net/browse/APPC-2503)
Tickets related to this pull-request: [APPC-2503](https://aptoide.atlassian.net/browse/APPC-2503)
**Questions:**
> [APPC-2503] Add support for Device ID

- app/src/main/java/com/asfoundation/wallet/repository/IpCountryCodeProvider.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/AsfInAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/BdsInAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/MergedAppcoinsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/MergedAppcoinsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/MergedAppcoinsView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyFragment.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyInteract.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
- app/src/test/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractorTest.java
Hotfixes for release where it fixes APPC payments and changes one exchanges endpoint
> hotfix/APPC Payments fix

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
- app/src/main/res/layout-land/error_top_up_layout.xml
- app/src/main/res/layout-land/support_error_layout.xml
- app/src/main/res/layout/error_top_up_layout.xml
- app/src/main/res/layout/support_error_layout.xml
- app/src/main/res/values/strings.xml
Adds a new error message for unverified wallets flagged for fraud with a button to navigate to the verification screen
No
- AdyenPaymentPresenter.kt
- AdyenTopUpPresenter.kt
- Try to pay with a blocked wallet, with the following card:
number:  4000 0200 0000 0000 
date: 03/30
cvc: 737
- Make a payment with trivial drive
- Make a top up payment
https://aptoide.atlassian.net/browse/APPC-2463
> [feature/APPC 2463] Adyen fraud message

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/verification/VerificationRepository.kt
What does this PR do?
Fixes fraud flow, removing the blocked wallet check 
Database changed?
No
Where should the reviewer start?
- AdyenPaymentPresenter.kt
- AdyenTopUpPresenter.kt
How should this be manually tested?
- Try to pay with a verified and an unverified wallet, with the following card:
number: 4000 0200 0000 0000
date: 03/30
cvc: 737
- Make a payment with trivial drive
- Make a top up payment
What are the relevant tickets?
https://aptoide.atlassian.net/browse/APPC-2463
> [APPC-2463] Fix for Fraud flow

- app/src/main/res/drawable/wallet_logo_background.xml
- app/src/main/res/layout-land/adyen_credit_card_layout.xml
- app/src/main/res/layout-land/adyen_credit_card_pre_selected.xml
- app/src/main/res/layout-land/fragment_carrier_confirm.xml
- app/src/main/res/layout-land/fragment_carrier_verify_phone.xml
- app/src/main/res/layout-land/fragment_share_payment_link.xml
- app/src/main/res/layout-land/merged_appcoins_layout.xml
- app/src/main/res/layout-land/payment_methods_layout.xml
- app/src/main/res/layout-land/wallet_logo_layout.xml
- app/src/main/res/layout/activity_iab.xml
- app/src/main/res/layout/adyen_credit_card_layout.xml
- app/src/main/res/layout/adyen_credit_card_pre_selected.xml
- app/src/main/res/layout/fragment_share_payment_link.xml
- app/src/main/res/layout/merged_appcoins_layout.xml
- app/src/main/res/layout/payment_methods_layout.xml
- app/src/main/res/layout/wallet_logo_layout.xml
Adds layout with wallet_logo and adds it to payment_methods_layout
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-2523](https://aptoide.atlassian.net/browse/MOB-2523)
Tickets related to this pull-request: [MOB-2523](https://aptoide.atlassian.net/browse/MOB-2523)
**Questions:**
No.
> [APPC-2523] Wallet logo on payments

- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapper.kt
Fixes an issue where credit card holders for US were not being shown the billing address screen.
Buy something with credit card and VPN to US and check that the billing address flow is now being shown correctly.
[APPC-2676](https://aptoide.atlassian.net/browse/APPC-2676)
> [bugfix/APPC-2676] US Billing Address Bug

- app/src/main/AndroidManifest.xml
Adds autoVerify to OSP which is needed to validate Android 12 Web Intent Resolution. 
No
This should be tested and only accepted once the json endpoint is done from the backend/infrastructure side. Once it is done, you can also manually test this by following these instructions: https://developer.android.com/about/versions/12/web-intent-resolution#manually-invoke-domain-verification
[APPC-2650](https://aptoide.atlassian.net/browse/APPC-2650)
> [task/APPC-2650] Android 12 Web Intent Resolution support

- app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
Adds support for a list of codapay intents.
No
The only way to test these new intents is to ask someone to enable it on dev and check if the intent works. I've tested for GO-PAY with a VPN to Indonesia and with the Gojek app.
[APPC-2740](https://aptoide.atlassian.net/browse/APPC-2740)
> [feature/APPC-2740] Added support for more CodaPay intents

- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
Fixes an issue where transaction details were empty on transactions with large amounts.
No
Check a big transaction (>1000 APPC) and see if the details are now shown correctly.
[APPC-2714](https://aptoide.atlassian.net/browse/APPC-2714)
> [bugfix/APPC-2714] Empty transaction details on large amounts

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyFragment.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/status/CarrierPaymentNavigator.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyNavigator.kt
- app/src/main/res/layout-land/support_error_layout.xml
- app/src/main/res/layout/support_error_layout.xml
- app/src/main/res/values/strings.xml
Redirects a verified wallet that encounters a FRAUD error when paying with CC to the verification screen.
No
Test both flows with Credit Card marked as FRAUD: one with a verified wallet and another with an unverified wallet and check if it behaves as expected.
[APPC-2766](https://aptoide.atlassian.net/browse/APPC-2766)
> [feature/APPC-2766] Redirect Verified wallet with Fraud to CC verification

- app/src/main/res/layout-land/payment_methods_layout.xml
Fixes issue with payment method list in IAP landscape.
No
Go to an IAP and once payment methods appears, switch to landscape. The payment methods list should be displayed correctly.
[APPC-2749](https://aptoide.atlassian.net/browse/APPC-2749)
> [bugfix/APPC-2749] IAP Landscape List

- app/src/main/java/com/asfoundation/wallet/promotions/PromotionsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/promotions/model/Promotion.kt
- app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/list/PromotionsController.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/list/model/DefaultModel.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/list/model/ProgressModel.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/list/model/PromoCodeModel.kt
- app/src/main/res/drawable/promotions_promo_code_date_background.xml
- app/src/main/res/drawable/promotions_promo_code_tag_background.xml
- app/src/main/res/drawable/rectangle_promotions_promo_code.xml
- app/src/main/res/layout/item_promotions_default.xml
- app/src/main/res/layout/item_promotions_progress.xml
- app/src/main/res/layout/item_promotions_promo_code.xml
- app/src/main/res/layout/item_promotions_referrals.xml
- app/src/main/res/layout/perks_content.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Implements promo code item in promotions.
Layout changes in the other items like default, progress to add some consistency and fixed empty app name use case.
No
- PromotionsMapper.kt 
- PromoCodeModel.kt
- item_promotions_promo_code.xml
- Add a promo code (megapack)
- Check the promotions perk list and check if promo code perk is highlighted 
Tickets related to this pull-request: https://aptoide.atlassian.net/browse/APPC-2762
> [feature/APPC-2762] Promotional code highlight in promotions

- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
- app/src/main/java/com/asfoundation/wallet/ui/transactions/models/TransactionModel.kt
Attemps to fix issue with value sign in transaction list and transaction details.
No
Check every type of transaction (including refunds/reverts) and check that the sign is displayed as expected (both on transaction list and transaction details).
[APPC-2704](https://aptoide.atlassian.net/browse/APPC-2704)
> [bugfix/APPC-2704] Fix transactions sign

- app/build.gradle
- app/src/main/java/com/asfoundation/wallet/logging/DebugReceiver.kt
- app/src/main/java/com/asfoundation/wallet/logging/WalletLogger.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
- app/src/main/java/com/asfoundation/wallet/util/Log.kt
Targets API 30 and makes necessary changes to actually build the project.
No
Just check if generally there's no problems with the app.
[APPC-2742](https://aptoide.atlassian.net/browse/APPC-2742)
> [task/APPC-2742] Target API 30

- app/src/main/java/com/asfoundation/wallet/analytics/RakamAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
- app/src/main/java/com/asfoundation/wallet/di/RepositoryModule.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/change_wallet/ChangeActiveWalletDialogFragment.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/change_wallet/ChangeActiveWalletDialogViewModel.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/PromoCodeBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/PromoCodeBottomSheetViewModel.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCode.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeBonusResponse.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeDatabase.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeEntity.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeLocalDataSource.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeRepository.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeResponse.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/GetCurrentPromoCodeUseCase.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/ObserveCurrentPromoCodeUseCase.kt
- app/src/main/res/layout/fragment_change_active_wallet.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
Adds a new message to when a user enters a promo code with bonus only for a specific app. Also improves and refactors parts of the code.
No
Test the promo code feature and insert a code with and without a specific app bonus to see the different messages.
[APPC-2802](https://aptoide.atlassian.net/browse/APPC-2802)
> [task/APPC-2802] Promo code message with App Name

- app/src/main/java/com/asfoundation/wallet/logging/send_logs/SendLogsRepository.kt
- app/src/main/java/com/asfoundation/wallet/logging/send_logs/SendLogsResponseBody.kt
Adds missing argument x-amz-security-token to upload_logs request
No
Flow on how to test this or QA Tickets related to this use-case: [APPC-2816](https://aptoide.atlassian.net/browse/APPC-2816)
Tickets related to this pull-request: [APPC-2816](https://aptoide.atlassian.net/browse/APPC-2816)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new libs, new keys, etc.) N/A
> [bugfix] Fix send logs

- skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt
- skills/src/main/java/cm/aptoide/skills/model/LoginRequest.kt
- skills/src/main/java/cm/aptoide/skills/repository/LoginRepository.kt
- skills/src/main/java/cm/aptoide/skills/usecase/LoginUseCase.kt
Adds ticket_id to login request body
No
Tickets related to this pull-request: [ESKL-148](https://aptoide.atlassian.net/browse/ESKL-148)
> [ESKL-148]Added ticket_id to LoginRequest

- app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
- app/src/main/java/com/asfoundation/wallet/entity/WalletHistory.java
- app/src/main/java/com/asfoundation/wallet/repository/TransactionMapper.kt
- app/src/main/java/com/asfoundation/wallet/repository/TransactionsDatabase.kt
- app/src/main/java/com/asfoundation/wallet/repository/entity/TransactionEntity.kt
- app/src/main/java/com/asfoundation/wallet/transactions/Transaction.java
- app/src/main/java/com/asfoundation/wallet/transactions/TransactionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
- app/src/main/res/layout/activity_transaction_detail.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/asfoundation/wallet/transactions/TransactionsMapperTest.kt
Shows order ID on Transaction Details if reference is not null. 
Yes (TransactionEntity migration)
- TransactionDetailActivity.java
Check transaction details and see if the order ID is showing up. 
https://aptoide.atlassian.net/browse/APPC-2789
> [feature/APPC-2789] Game order reference transaction details

- app/src/main/java/com/asfoundation/wallet/repository/TransactionsDatabase.kt
> [bugfix] migrations order reference

- app/src/main/java/com/asfoundation/wallet/di/RepositoryModule.kt
- app/src/main/java/com/asfoundation/wallet/di/UseCaseModule.kt
- app/src/main/java/com/asfoundation/wallet/ewt/EwtAuthenticatorService.kt
- app/src/main/java/com/asfoundation/wallet/ui/backup/success/BackupSuccessLogRepository.kt
- app/src/main/java/com/asfoundation/wallet/ui/backup/success/BackupSuccessLogUseCase.kt
Creates repository to send wallet backup information to backend. Not being used yet, but the UseCase is ready
No
- BackupSuccessLogRepository.kt
- BackupSuccessLogUseCase.kt
N/A for now
https://aptoide.atlassian.net/browse/APPC-2783
> [task/APPC-2783] wallet backup log

- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
- app/src/main/res/layout/activity_transaction_detail.xml
Fixes order id constraints and adds copy to clipboard on order id click
No
Open a transaction with order id, check layout and copy it to clipboard
https://aptoide.atlassian.net/browse/APPC-2789
> [hotfix/APPC-2789] Order id layout fix

- app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/common/ToolbarTextSwitcher.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/wallets/bottomsheet/SettingsWalletsBottomSheetPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/wallets/WalletsInteract.kt
- app/src/main/res/layout/fragment_my_wallets.xml
- app/src/main/res/layout/layout_toolbar_text_switcher.xml
- app/src/main/res/values/styles_views.xml
Fixes issue with My Wallets empty state and text switcher animations.
No
Check both my wallets empty state and if text switcher animations work correctly.
[APPC-2849](https://aptoide.atlassian.net/browse/APPC-2849)
> [hotfix/APPC-2849] Issue with My Wallets empty state and text switcher

- app/src/main/java/com/asfoundation/wallet/di/InteractorModule.kt
- app/src/main/java/com/asfoundation/wallet/home/HomeViewModel.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsFragment.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsViewModel.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/list/WalletsController.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/list/model/ActiveWalletModelGroup.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/list/model/WalletInfoModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/common/ToolbarTextSwitcher.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/wallets/bottomsheet/SettingsWalletsBottomSheetPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/wallets/WalletsInteract.kt
- app/src/main/java/com/asfoundation/wallet/ui/wallets/WalletsModel.kt
- app/src/main/java/com/asfoundation/wallet/wallets/db/WalletInfoDao.kt
- app/src/main/java/com/asfoundation/wallet/wallets/repository/WalletInfoRepository.kt
> 2.3.0/hotfixes

- app/src/main/java/com/asfoundation/wallet/ui/transact/TransferInteractor.kt
fixes ETH and APPC transfer problems
No
- TransferInteractor.kt
make an ETH or APPC transfer
> [bugfix/ETH-transfers] fixes ETH and APPC transfer problems

- app/src/main/java/com/asfoundation/wallet/ui/transact/TransferInteractor.kt
Reverts Catappult/appcoins-wallet-android#235
> Revert "[bugfix/ETH-transfers] fixes ETH and APPC transfer problems"

- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
- app/src/main/res/layout/activity_transaction_detail.xml
"From" and "to" fields on transaction details.
No
Transaction details
https://aptoide.atlassian.net/browse/APPC-2797
> Transactions details - from/to

- app/src/main/res/layout/settings_promo_code_bottom_sheet_layout.xml
- app/src/main/res/values/strings.xml
Fixes two tickets regarding the promo code.
- the 16char limit in the code (APPC-2800)
- the replace button width in some languages (APPC-2809)
No
- try to put more than 16 chars in a promo code
- Test in Portuguese device to check the replace button 
https://aptoide.atlassian.net/browse/APPC-2800
https://aptoide.atlassian.net/browse/APPC-2809
> [bugfix/APPC-2800 and bugfix/APPC-2809] Promo Code bugs

- app/src/main/java/com/asfoundation/wallet/promo_code/SettingsPreferencePromoCodeState.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeRepository.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeResponse.kt
Updates the endpoint, since the expired field is no longer nullable, so the check needed to change
No
test with an expired and an active promo code (megapack2 and megapack, respectively )
https://aptoide.atlassian.net/browse/APPC-2913
> [APPC-2913] Update promo code endpoint

- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
Fix: missing sender information on transaction details for appc-c.
No
Transactions details for APPC-C.
> Sender on appc-c

- app/build.gradle
The "File not found" issue faced during the Gradle sync with a fresh installation on M1 machine. This change fixes the issue and is compatible with other arch machines.
No
Run the Gradle sync for the project
> Fix the path to resolve the missing file error

- app/src/main/java/com/asfoundation/wallet/App.kt
- app/src/main/java/com/asfoundation/wallet/analytics/JoinedAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/analytics/SentryAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/analytics/SentryEventLogger.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/di/InteractorModule.kt
- app/src/main/java/com/asfoundation/wallet/di/RepositoryModule.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/PromotionsModuleNew.kt
- app/src/main/java/com/asfoundation/wallet/repository/WalletRepository.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/wallets/repository/WalletInfoRepository.kt
- app/src/main/java/com/asfoundation/wallet/wallets/repository/WalletInfoResponse.kt
These changes add additional context info to the crashes sent to the Sentry
Should make debugging much easier
No
1. Start the app
2. Perform any actions for a while
3. Remove **all** wallets
4. Go to settings initiating the guaranteed crash
5. Find your crash in the Sentry
Tickets related to this pull-request: [APPC-2915](https://aptoide.atlassian.net/browse/APPC-2915)
> [APPC-2915] Send more logs

- app/src/main/res/values/strings.xml
- skills/src/main/res/values/strings.xml
merges changes from translations update
No
> [strings] strings conflicts merge from translation_updates branch

- app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationActivity.kt
fixes GamificationActivity crash on activity opening
https://aptoide.atlassian.net/browse/APPC-2864
> [refactor/hilt] fixes GamificationActivity crash

- app/src/main/java/com/asfoundation/wallet/ui/balance/TransactionDetailActivity.java
Replace hardcoded string with the one from resources
Yes
Change a language and open transaction details.
Tickets related to this pull-request: [APPC-2965](https://aptoide.atlassian.net/browse/APPC-2965)
> [APPC-2965] Replace hardcoded string

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroFragment.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroPresenter.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroView.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/paypal/VerificationPaypalViewModel.kt
- billing/build.gradle
- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapper.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/PaymentInfoModel.kt
- billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapperTest.kt
Remove the architecture rely on inheritance between Adyen `PaymentMethod` and `StoredPaymentMethod` classes.
No
Check the top-up and payment flows, should be unchanged
Tickets related to this pull-request: [APPC-2955](https://aptoide.atlassian.net/browse/APPC-2955)
> [APPC-2955] Refactor the Adyen SDK usage

- app/src/main/java/com/asfoundation/wallet/billing/share/BdsShareLinkRepository.kt
- app/src/main/java/com/asfoundation/wallet/di/annotations/DeeplinkRetrofit.kt
- app/src/main/java/com/asfoundation/wallet/di/api/microservices/BrokerApiModule.kt
- app/src/main/java/com/asfoundation/wallet/di/api/microservices/DeeplinkApiModule.kt
fixes ask someone to pay deeplink api path
No
Go to a payment flow, select ask someone to pay and generate link (if the link is created, its working)
> [hotfix] fixes ask someone to pay deeplink api path

- app/src/main/java/com/asfoundation/wallet/nfts/ui/nftTransactDialog/NFTTransactDialogFragment.kt
- app/src/main/java/com/asfoundation/wallet/nfts/ui/nftTransactDialog/NFTTransactDialogModule.kt
- app/src/main/java/com/asfoundation/wallet/nfts/ui/nftdetails/NFTDetailsModule.kt
- app/src/main/java/com/asfoundation/wallet/nfts/usecases/EstimateNFTSendGasUseCase.kt
- app/src/main/java/com/asfoundation/wallet/nfts/usecases/SendNFTUseCase.kt
Fixes crash on NFT transaction bottom sheet
https://aptoide.atlassian.net/browse/APPC-2806
> Bugfix/ NFTs app crash hilt

- app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsFragment.kt
Prevent remove of the only wallet
No
Try to remove all wallets. You should not be able to do this
Tickets related to this pull-request: [APPC-2936](https://aptoide.atlassian.net/browse/APPC-2936)
> [APPC-2936] Don't allow to remove the last wallet

- app/src/main/java/com/asfoundation/wallet/repository/TransactionRepository.java
- app/src/main/java/com/asfoundation/wallet/service/Web3jKeystoreAccountService.java
- build.gradle
(Depends on the Web3j PR)
On-chain transactions update to use EIP-1559 transactions (type 2).
The on-chain transactions affected were:
- Eth transfers 
- APPC transfers 
- APPC approve (purchases) 
- APPC buy (purchases)
No
Eth transfers, APPC transfers, APPC purchases.
https://aptoide.atlassian.net/browse/APPC-2901
> EIP-1559 Transactions

- app/src/main/java/com/asfoundation/wallet/ui/gamification/CurrentLevelViewHolder.kt
- app/src/main/java/com/asfoundation/wallet/util/CurrencyFormatUtils.kt
- app/src/main/res/drawable/space_background_card.xml
- app/src/main/res/layout/current_level_card.xml
- app/src/test/java/com/asfoundation/wallet/util/CurrencyFormatUtilsTest.kt
Fix and update the Gamification card UI.
No
Start review by commits.
Open the gamification view and check the UI.
Tickets related to this pull-request: [APPC-2947](https://aptoide.atlassian.net/browse/APPC-2947)
> Appc 2947 gamification UI

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
Allows Codapay webview to open a selection of external apps to continue the payment. For Indonesia and India.
no
Payment flows that should be tested:
Indonesia:
- GoPay 
India, (choosing Paytm UPI):
- Paytm UPI
- PhonePe
- BHIM
https://aptoide.atlassian.net/browse/APPC-2982
> Codapay launch external apps

- app/src/main/java/com/asfoundation/wallet/analytics/IndicativeAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/analytics/IndicativeEventLogger.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
The Indicative user specific parameters were missing after the hilt development
No
Check in the logcat if Indicative events are being sent with the parameters.
https://aptoide.atlassian.net/browse/APPC-3018
> Indicative missing user params

- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
Updated links for T&C and Privacy policy.
No
Open T&C and privacy webview through the settings.
https://aptoide.atlassian.net/browse/APPC-2973
> Legal docs update

- app/build.gradle
- app/src/debug/res/values/booleans.xml
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenCardWrapper.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
- app/src/main/java/com/asfoundation/wallet/util/AdyenCardView.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroFragment.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroPresenter.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroView.kt
- app/src/main/res/layout-land/fragment_adyen_top_up.xml
- app/src/main/res/layout/fragment_adyen_top_up.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_adyen.xml
- app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
- billing/build.gradle
- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapper.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenSerializer.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/PaymentInfoModel.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/PaymentModel.kt
- billing/src/main/java/com/appcoins/wallet/billing/common/BillingErrorMapper.kt
- billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepositoryTest.kt
- billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapperTest.kt
- build.gradle
- skills/build.gradle
Update Adyen SDK to the most recent version
No
Check al the payments and to ups with the Adyen
Tickets related to this pull-request: [APPC-2895](https://aptoide.atlassian.net/browse/APPC-2895)
> [APPC-2895] Update Adyen SDK

- app/src/main/java/com/asfoundation/wallet/nfts/repository/NFTRepository.kt
- app/src/main/java/com/asfoundation/wallet/nfts/ui/nftdetails/NFTDetailsFragment.kt
Enables transfer of ERC 1155 NFTs
The tester should have a ERC 1155 NFT and try to transfer it to other wallet
Tickets related to this pull-request: [APPC-3046](https://aptoide.atlassian.net/browse/APPC-3046)
> Transfer ERC 1155

- app/src/main/java/com/asfoundation/wallet/backup/repository/preferences/BackupSystemNotificationPreferences.kt
- app/src/main/java/com/asfoundation/wallet/backup/use_cases/SaveDismissSystemNotificationUseCase.kt
- app/src/main/java/com/asfoundation/wallet/backup/use_cases/ShouldShowBackupTriggerUseCase.kt
- app/src/main/java/com/asfoundation/wallet/backup/use_cases/ShouldShowSystemNotificationUseCase.kt
- app/src/main/java/com/asfoundation/wallet/backup/use_cases/UpdateWalletPurchasesCountUseCase.kt
- app/src/main/java/com/asfoundation/wallet/interact/DeleteWalletInteract.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
fixes backup android notification and adds time (30 day) logic to be consistent with the logic in the triggers
No
- ShouldShowSystemNotificationUseCase.kt
- make multiple payments and check the notification (should only appear every 2 payments, not every payment)
- the dismiss on the notification should "snooze" for 30 days
https://aptoide.atlassian.net/browse/APPC-3056
> [feature/APPC-3056] Fix backup notification

- app/src/main/java/com/asfoundation/wallet/backup/entry/BackupEntryViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/backup/save_on_device/BackupSaveOnDeviceDialogViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/backup/save_options/BackupSaveOptionsViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/change_currency/SettingsCurrencyPreference.kt
- app/src/main/java/com/asfoundation/wallet/change_currency/bottom_sheet/ChooseCurrencyBottomSheetViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/main/MainViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/change_wallet/ChangeActiveWalletDialogViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/more/MoreDialogViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/token/TokenInfoDialogViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/nfts/ui/nftTransactDialog/NFTTransactDialogViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/nfts/ui/nftdetails/NFTDetailsViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/SettingsPreferencePromoCodeState.kt
- app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/transactions/PerkBonusAndGamificationService.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/paypal/VerificationPaypalViewModelFactory.kt
- app/src/main/java/com/asfoundation/wallet/viewmodel/TransactionDetailModule.kt
- app/src/main/java/com/asfoundation/wallet/viewmodel/TransferConfirmationModule.kt
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Update to:
- All androidx libraries exept androidx.navigation, 
- Target and compile sdk to 31 (android 12), 
- Kotlin version
- Gradle version
Mainly build.gradle
Complete regression tests would be ideal.
https://aptoide.atlassian.net/browse/APPC-3106
> AndroidX dependencies update

- app/src/main/java/com/asfoundation/wallet/analytics/TaskTimer.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/di/AppModule.kt
- app/src/main/java/com/asfoundation/wallet/ui/Erc681Receiver.kt
- app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/MergedAppcoinsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
Add analytic events to gather the payment flow timings.
No
Check by commits
Test OSP and SDK purchases with and without preselected payment method for APPC-C, PP and CC.
Check in the logs if correct events sent.
Tickets related to this pull-request: [APPC-3118](https://aptoide.atlassian.net/browse/APPC-3118)
> [APPC-3118] Send timings measures to the indicative and rakam

- app/src/main/java/com/asfoundation/wallet/eskills/withdraw/WithdrawFragment.kt
- app/src/main/java/com/asfoundation/wallet/eskills/withdraw/WithdrawViewModel.kt
- app/src/main/java/com/asfoundation/wallet/eskills/withdraw/repository/WithdrawRepository.kt
- app/src/main/java/com/asfoundation/wallet/eskills/withdraw/usecases/GetAvailableAmountToWithdrawUseCase.kt
- app/src/main/java/com/asfoundation/wallet/eskills/withdraw/usecases/WithdrawToFiatUseCase.kt
- app/src/main/res/layout-land/layout_withdraw_success.xml
- app/src/main/res/layout/layout_withdraw_error.xml
- app/src/main/res/layout/layout_withdraw_success.xml
Eskills messages update for success screen and error edge cases.
Check first commit.
Withdraw eskills credits with success; 
Try withdrawing without enough funds; 
Try withdrawing less than the minimum allowed.
https://aptoide.atlassian.net/browse/APPC-3117
> Eskills messages correction

- app/src/main/java/com/asfoundation/wallet/main/MainActivityNavigator.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
- app/src/main/java/com/asfoundation/wallet/transfers/EtherTransactionBottomSheetNavigator.kt
Fix navigation to home screen for Android 12.
Complete an eth transfer, click "got it".
Complete a topup, click "ok".
https://aptoide.atlassian.net/browse/APPC-3192
> [APPC-3192] Fix buttons to Home Android 12

- app/src/main/java/com/asfoundation/wallet/eskills/withdraw/WithdrawFragment.kt
Changed the message on eskills withdraw when amount is zero.
Withdraw with zero amount.
https://aptoide.atlassian.net/browse/APPC-3117
> Fix amount withdraw message

- app/src/main/java/com/asfoundation/wallet/home/ui/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/home/ui/HomeNavigator.kt
- app/src/main/java/com/asfoundation/wallet/home/ui/HomeViewModel.kt
- app/src/main/java/com/asfoundation/wallet/home/ui/list/HomeListClick.kt
- app/src/main/java/com/asfoundation/wallet/home/ui/list/header/HomeWalletInfoModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/balance/BalanceInteractor.kt
- app/src/main/java/com/asfoundation/wallet/wallets/domain/WalletBalance.kt
- app/src/main/java/com/asfoundation/wallet/wallets/repository/BalanceRepository.kt
- app/src/main/res/drawable/appbar_background_large_new.xml
- app/src/main/res/drawable/home_bar_separator_corner.xml
- app/src/main/res/drawable/pull_up_home_bar.xml
- app/src/main/res/layout-land/item_home_wallet_info.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/item_card_notification.xml
- app/src/main/res/layout/item_home_header_group.xml
- app/src/main/res/layout/item_home_wallet_info.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles_my_wallets.xml
Home UI changes:
- Removed send/receive button from Home 
- New UI separator on balance 
- Only showing Appc-credits on Home 
Mostly home layouts.
- Check Home UI in portrait/landscape mode 
- Check Home with a notification
https://aptoide.atlassian.net/browse/APPC-3083
> [APPC 3082] Simplify home crypto

- gradle.properties
To fix the OutOfMemory problem on Jenkins. Increases the max heap size to 2GB
Run a build job after having this in dev
> Increase heap size

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapper.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenSerializer.kt
- billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapperTest.kt
Add handling for the new "threeDS2" action type.
No
Tickets related to this pull-request: [APPC-3211](https://aptoide.atlassian.net/browse/APPC-3211)
> [APPC-3211] Add handling for the new "threeDS2" action type

- app/src/main/java/com/asfoundation/wallet/di/api/BackendApiModule.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallets/repository/WalletInfoResponse.kt
Fix the type of the last backup date
No
Tickets related to this pull-request: [APPC-3284](https://aptoide.atlassian.net/browse/APPC-3284)
> [APPC-3284] Add last backup date handling

- build.gradle
Update intercom version to fix chat messages not being received. The connection was closing after some minutes with the chat opened.
No
Open intercom chat in dev, send messages and see if they are received in the phone.
https://aptoide.atlassian.net/browse/APPC-3169
> Update intercom version

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/util/AdyenCardView.kt
- build.gradle
Fix issues with the 3DS and redirection navigations.
No
Try to make payments with the 3DS credit card.
Tickets related to this pull-request: [APPC-3303](https://aptoide.atlassian.net/browse/APPC-3303)
> [APPC-3303] 3DS 2 secure payment flow

- app/src/main/java/com/asfoundation/wallet/di/api/microservices/BrokerApiModule.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/PromoCodeResult.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/SettingsPreferencePromoCodeState.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetViewModel.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCode.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeBonusResponse.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeDatabase.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeEntity.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeLocalDataSource.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeModule.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/repository/PromoCodeRepository.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/GetCurrentPromoCodeUseCase.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/GetStoredPromoCodeResultUseCase.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/GetUpdatedPromoCodeUseCase.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/SetPromoCodeUseCase.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/use_cases/VerifyAndSavePromoCodeUseCase.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/database/AppCoinsOperationsModule.kt
- app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
Removed MS check from promo codes. Only relies on BE as source of truth to determine promo code validity and expiry.
Error 409 handled for expiry.
Yes
Test to promo codes in all possible states: active, expired, wrong one, expiring soon.
Test db migration to new schema.
https://aptoide.atlassian.net/browse/APPC-3269
https://aptoide.atlassian.net/browse/APPC-3268
> [APPC-3269] Promo codes without MS

- app/build.gradle
- app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
- app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
- app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordFragment.kt
- app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordNavigator.kt
Fix crash on wallet restore during Onboarding.
No
Tickets related to this pull-request: [APPC-3318](https://aptoide.atlassian.net/browse/APPC-3318)
> Fix NPE crash on restore [Do not Merge!]

- app/src/main/java/com/asfoundation/wallet/analytics/SentryAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivityPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroPresenter.kt
Make sure that all errors presented to user with the support button available are logged to the Sentry.
No
Tickets related to this pull-request: [APPC-3313](https://aptoide.atlassian.net/browse/APPC-3313)
> [APPC-3313] Create error log entry every time an error is shown to users on the Wallet

- app/src/main/java/com/asfoundation/wallet/promotions/ui/PromotionsFragment.kt
When the wallet didn't have promotions available yet, it was showing a blank screen.
No
Create a new wallet. Check the promotions page.
https://aptoide.atlassian.net/browse/APPC-3329
> [APPC-3329] Fix locked promotion screen not showing

- app/src/main/java/com/asfoundation/wallet/app_start/AppStart.kt
- app/src/main/java/com/asfoundation/wallet/app_start/FirstTopApp.kt
- app/src/main/java/com/asfoundation/wallet/app_start/FirstUtm.kt
- app/src/main/java/com/asfoundation/wallet/app_start/Probes.kt
- app/src/main/java/com/asfoundation/wallet/app_start/Repositories.kt
- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragment.kt
- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragmentNavigator.kt
- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/top_app/OnboardingTopAppFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/top_app/OnboardingTopAppNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/top_app/OnboardingTopAppViewModel.kt
- app/src/main/java/com/asfoundation/wallet/repository/WalletRepository.kt
- app/src/main/res/layout-land/onboarding_top_app_fragment.xml
- app/src/main/res/layout/onboarding_top_app_fragment.xml
- app/src/main/res/navigation/nav_bar_graph.xml
- app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
- app/src/test/java/com/asfoundation/wallet/app_start/FirstTopAppUseCaseTest.kt
- app/src/test/java/com/asfoundation/wallet/app_start/FirstUtmUseCaseTest.kt
No
Instal 1 or more top apps, and start the Wallet from a fresh install .
Tickets related to this pull-request: [APPC-3325](https://aptoide.atlassian.net/browse/APPC-3325)
> [APPC-3325] Back to the game no gps

- app/src/main/res/layout/item_promotions_default.xml
- app/src/main/res/layout/item_promotions_future.xml
- app/src/main/res/layout/item_promotions_progress.xml
- app/src/main/res/layout/item_promotions_promo_code.xml
- app/src/main/res/layout/item_promotions_referrals.xml
- app/src/main/res/values/styles.xml
Perk color changed to blue to match new design. 
Vertical spacing decreased.
No
Check promotions page
https://aptoide.atlassian.net/browse/APPC-3336
> [APPC-3336] Perks color lineup

- app/src/main/java/com/asfoundation/wallet/main/PendingIntentNavigator.kt
fixes deeplinks that were part of the main activity.
No
- trigger the “almost next level” or the “new level”  notification
- clicking on it should bring the user to promotions and not the home
https://aptoide.atlassian.net/browse/APPC-3338
> [bugfix/APPC-3338] Fixes navigation with deeplinks

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/di/AnalyticsModule.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/util/LogInterceptor.java
Handle error and analytics events for 3ds authentications.
AdyenPaymentPresenter
Check events sent on 3ds.
https://aptoide.atlassian.net/browse/APPC-3376
> [APPC-3376] 3DS events

- skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
> Missing create ticket and payment call

- app/src/main/java/com/asfoundation/wallet/home/ui/list/transactions/empty/EmptyTransactionsModel.kt
Implements an auto scroll that changes page every 3 seconds in the home empty screen
No
- Create a new wallet
- Go to home
- Check that the empty screen changes every 3 seconds
https://aptoide.atlassian.net/browse/APPC-3400
> [feature/APPC-3400] Home screen auto scroll

- app/src/main/java/com/asfoundation/wallet/app_start/AppStart.kt
- app/src/main/java/com/asfoundation/wallet/app_start/Probes.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/PendingPurchaseFlowUseCase.kt
- app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
On the first install, we want to differentiate if a user is coming from OSP or not.
If its not from the OSP, it will be tagged as Other.
No
- Open the wallet on first start and check the event parameters
> Integration flow on first start 

- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragment.kt
- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarViewModel.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogFragment.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogNavigator.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/common/WalletButtonView.kt
- app/src/main/res/layout-land/fragment_onboarding.xml
- app/src/main/res/layout-land/onboarding_value_propositions.xml
- app/src/main/res/layout/fragment_create_wallet_dialog_layout.xml
- app/src/main/res/layout/fragment_my_wallets_toolbar.xml
- app/src/main/res/layout/fragment_onboarding.xml
- app/src/main/res/layout/item_appcoins_application.xml
- app/src/main/res/layout/item_card_notification.xml
- app/src/main/res/layout/onboarding_buttons.xml
- app/src/main/res/layout/onboarding_terms_conditions.xml
- app/src/main/res/navigation/onboarding_graph.xml
Changes the onboarding animation as a temporary solution (the flow is now seperated from the create wallet dialog we have for the rest of the app) and changes the animation of that dialog.
Also fixes a few reported color issues 
No
- OnboardingFragment.kt
> Onboarding animation changes

- skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
- skills/src/main/java/cm/aptoide/skills/usecase/GetTopUpListUseCase.kt
Fixes order or skills verification without major changes to code that were blocking UI
No
> fixed order of eskills verification

- app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogNavigator.kt
- app/src/main/res/navigation/onboarding_graph.xml
Fixes the onboarding navigation when exiting the wallet creation animation
No
- Open the wallet and try the 3 different navigations (normal onboarding, first install flow, and recover)
> Fixes onboarding navigation

- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
Deactivates topup abtesting requests as it was no longer used. 
No
Check if there is no requests made to the abtesting endpoint
https://aptoide.atlassian.net/browse/APPC-3433
> Deactivate Topup abtesting

- app/src/main/java/com/asfoundation/wallet/util/OneStepTransactionParser.kt
- app/src/test/java/com/asfoundation/wallet/util/OneStepTransactionParserTest.kt
If the OSP doesn't specifies the price and currency, then the wallet fetches that information from productV2 details.
No
OneStepTransactionParser
Make an Oil purchase from the new trivial drive.
https://aptoide.atlassian.net/browse/APPC-3420
> Optional Price and Currency OSPs

- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalIABViewModel.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalTopupFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalTopupViewModel.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/repository/PayPalV2Repository.kt
- bdsbilling/src/test/java/com/appcoins/wallet/bdsbilling/BillingPaymentProofSubmissionTest.kt
- billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepositoryTest.kt
When making a Paypal purchase, requests a new login if the current payment method selected on Paypal account is not valid.
No
PayPalV2Repository.kt
Make a Paypal purchase without enough balance, a new login will start to select a valid payment.
https://aptoide.atlassian.net/browse/APPC-3436
> [APPC-3436] Paypal request new login if needed

- skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
Disables buy button after click to make sure users don't make the same purchase twice.
https://aptoide.atlassian.net/browse/ESKL-282
> [ESKL-282] Disable buy button after click

- build.gradle
Flurry version update to 14.0.0
No
Start the app and check on flurry for the session
https://aptoide.atlassian.net/browse/APPC-3369
> [APPC-3369] Flurry version bump

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/PaymentType.java
- app/src/main/java/com/asfoundation/wallet/billing/analytics/BillingAnalytics.java
- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivityView.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsMapper.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
- billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
- build.gradle
Reverts Catappult/appcoins-wallet-android#460
> Revert "[APPC-3439] Google Pay"

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentAnalytics.kt
Consistency with the payment_method property between events.
No
Check events on Indicative
https://aptoide.atlassian.net/browse/APPC-3466
> [APPC-3466] Events payment method consistency

- app/src/main/res/layout/backup_entry_info.xml
Fixes a small layout inconsistency with the backup subtitle
No
https://aptoide.atlassian.net/browse/APPC-3506
> [bugfix/APPC-3506] Fix backup flow layout

- app/src/main/java/com/asfoundation/wallet/DevUtils.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
Reduces the time we wait before asking if the payment is finally completed.
This change should impact the first payment, especially the first PayPal payment, reducing for about 25% the user’s wait time.
The change is small in the getAuthorisedTransaction(), but most of this is codestyles changes.
No
- Make a first payment via a paypal 
- measure the time it takes since our loading appears to the time the success animation happens
https://aptoide.atlassian.net/browse/APPC-3511
> [task/APPC-3511] Pending user payment delay

- app/src/main/res/layout-land/onboarding_gp_install_fragment.xml
- app/src/main/res/layout/onboarding_gp_install_fragment.xml
Fixed buttons on smaller screens, causing the margins to be so big that the button would shrink too much
No
https://aptoide.atlassian.net/browse/APPC-3504
> [bugfix/APPC-3504] Onboarding from Google play buttons layout

- app/src/main/java/com/asfoundation/wallet/ui/transact/TransferFragment.kt
Fixed Overlapping icons in Send Money Fragment
No
- TransferFragment
Try to send money to wrong wallet address
Tickets related to this pull-request: [APPC-3531](https://aptoide.atlassian.net/browse/APPC-3531?atlOrigin=eyJpIjoiYTI4OTM0NzQzYmMzNGI0Nzg0NTYzNmM1MTJkM2RmY2QiLCJwIjoiaiJ9)
> [BugFix/ APPC-3531] Fixed Overlapping Icons

- app/build.gradle
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/fragment_settings.xml
No
Test if all settings items work
Tickets related to this pull-request: [APPC-3497](https://aptoide.atlassian.net/browse/APPC-3497)
> [APPC-3497] Settings items order

- app/src/main/java/com/asfoundation/wallet/change_currency/FiatCurrenciesRepository.kt
- app/src/main/java/com/asfoundation/wallet/change_currency/bottom_sheet/ChooseCurrencyBottomSheetData.kt
- app/src/main/java/com/asfoundation/wallet/change_currency/bottom_sheet/ChooseCurrencyBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/change_currency/bottom_sheet/ChooseCurrencyBottomSheetModule.kt
- app/src/main/java/com/asfoundation/wallet/change_currency/bottom_sheet/ChooseCurrencyBottomSheetViewModel.kt
- app/src/main/java/com/asfoundation/wallet/change_currency/list/model/FiatCurrencyModel.kt
- app/src/main/res/drawable/currency_flag_placeholder.xml
The app was crashing if a currency didn’t have a flag. 
No
To test, go to “change currency” and search for a currencies without flags. There should be a grey placeholder.
https://aptoide.atlassian.net/browse/APPC-3555
> [APPC-3555] Fix to prevent crash when a currency's flag is null

- airdrop/build.gradle
- app/build.gradle
- appcoinsRewards/build.gradle
- bdsbilling/build.gradle
- billing/build.gradle
- build.gradle
- commons/build.gradle
- ethereumj-android/build.gradle
- gamification/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- permissions/build.gradle
- settings.gradle
- skills/build.gradle
Gradle version catalog and convention plugins required an upgrade
- Regression tests
https://aptoide.atlassian.net/browse/APPC-3543
> [APPC-3543] updated gradle and kotlin version

- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetFirstPaymentMethodsUseCase.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/BdsInAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BdsBilling.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/Billing.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingRepository.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Starts sending the package_name in the /methods request.
No
Tickets related to this pull-request: [APPC-3559](https://aptoide.atlassian.net/browse/APPC-3559)
> [APPC-3559] OPS: Send package_name in request to get payment methods

- bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Version bump on /methods endpoint. Needed for applying the current endpoint changes.
No
> Methods api version bump

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Downgrades gradle version changed in #487, reducing from 8.0 to 7.5
No
> [task/APPC-3543] change gradle version

- app/src/main/java/com/asfoundation/wallet/billing/partners/PartnerAddressService.kt
Prioritizes GamesHub OemId, if available. Otherwise uses the game's OemId.
No
PartnerAddressService
Do a purchase with and without GamesHub installed.
https://aptoide.atlassian.net/browse/APPC-3591
> [APPC-3591] OemId with priority for GamesHub

- crowdin.yml
Updates the crowdin file to have the right path for the strings resources now that all changes are in dev
https://aptoide.atlassian.net/browse/APPC-3535
> Update strings crowdin path

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/home/ui/list/transactions/PerkModel.kt
- app/src/main/java/com/asfoundation/wallet/home/ui/list/transactions/TransactionModel.kt
- app/src/main/java/com/asfoundation/wallet/main/splash/SplashExtenderFragment.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogFragment.kt
- app/src/main/java/com/asfoundation/wallet/permissions/request/view/CreateWalletFragment.kt
- app/src/main/java/com/asfoundation/wallet/rating/finish/RatingFinishFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/localpayments/LocalTopUpPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/code/VerificationCodeFragment.kt
- convention/src/main/java/com/appcoins/wallet/convention/Config.kt
- convention/src/main/java/com/appcoins/wallet/convention/plugins/AndroidAppPlugin.kt
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WalletButtonView.kt
Version bumps to support compose.
No
https://aptoide.atlassian.net/browse/APPC-3569
> [APPC-3569] Version updates for Compose

- ui/common/src/main/res/values/strings.xml
> New strings - APPC-3525 and APPC-3571

- legacy/skills/src/main/res/values/strings.xml
> New Strings - e-Skills Referral Program

- ui/widgets/build.gradle.kts
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/HorizontalCardLazyList.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/VerticalCardLazyList.kt
Implement VertticalList base and HorizontalList base in UI/ widgets to make a base from carrousel
No
Use comando run into Compose to test this
Tickets related to this pull-request: [APPC-3583](https://aptoide.atlassian.net/browse/APPC-3583)
> [APPC-3583] Base carrousel

- legacy/skills/src/main/res/values/strings.xml
> New String - VPN error message

- ui/common/src/main/res/values/strings.xml
> New String  - VIP offer

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/res/layout-land/fragment_top_up_success.xml
- app/src/main/res/layout/fragment_iab_transaction_completed.xml
- app/src/main/res/layout/reward_payment_layout.xml
Payment and Topup fixes:
- message on payments not showing, 
- success animation on purchases with appc
- landscape success topup was cropped
No
https://aptoide.atlassian.net/browse/APPC-3669
> [APPC-3585] material3 fixes

- core/network/analytics/build.gradle.kts
- core/network/analytics/src/main/java/com/appcoins/wallet/core/network/analytics/AnalyticsApiModule.kt
- core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/api/AppDataApi.kt
- core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/model/AppData.kt
- core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/model/AppInfo.kt
- legacy/skills/build.gradle.kts
- legacy/skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
- legacy/skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt
- legacy/skills/src/main/java/cm/aptoide/skills/repository/AppMetaDataRepository.kt
- legacy/skills/src/main/java/cm/aptoide/skills/usecase/ReferralShareTextBuilderUseCase.kt
Improves overall referral code and onboarding copy.
Adds call to microservices to retrieve app name and download url (used in share referral activity ) 
No
- SkillsFragment
Purchase a ticket, when sharing your referral code, the message should have the game name, download url and referral code
Tickets related to this pull-request: [ESKL-313](https://aptoide.atlassian.net/browse/ESKL-313)
> Improves referral code copy

- legacy/skills/src/main/res/layout-land/loading_ticket_layout.xml
- legacy/skills/src/main/res/values/dimens.xml
Fixed waiting for players layout in landscape mode.
No
Test a live game in landscape mode (8 ball clash).
Tickets related to this pull-request: [ESKL-317](https://aptoide.atlassian.net/browse/ESKL-317)
> fix landscape waiting for players layout

- app/src/main/res/layout/onboarding_adyen_payment_fragment.xml
Fixes problem with landscape with Adyen CC payments
No
- Trigger the new onboarding payment flow
- rotate the screen on the splash screen (rotating is locked in the onboarding payment flow)
- try to input info in the adyen card to make a payment
https://aptoide.atlassian.net/browse/APPC-3671
> [APPC-3671] fixes landscape in onboarding flow

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetPaymentInfoModelUseCase.kt
- app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/AdyenApi.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
- legacy/billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepositoryTest.kt
Payment methods request with signing. 
No
Test CC and Paypal payments
https://aptoide.atlassian.net/browse/APPC-3638
> [APPC-3638] Payment methods request with signing

- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
- ui/widgets/src/gp/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
Fixed build variant stub with correct name.
> Build Variant fix

- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/local_payments/OnboardingLocalPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetTransactionStatusUseCase.kt
Fix problem with get Transactions Status and start job to transaction status in error case Too, and create validation to not create two instance to same job
No
Start a local Payment in Onboarding Flow
> BugFix Improve Local Payment

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
Adds the error_details on webView payments when an error occurs.
No
AdyenPaymentFragment.kt
Make a payment with an error on paypal (by not having a valid CC for example)
https://aptoide.atlassian.net/browse/APPC-3691
> [APPC-3691] error_details for webView payments

- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/AdyenApi.kt
Version bump to the adyen endpoint to the new version.
No
> Updated adyen endpoint versioning

- app/build.gradle.kts
> VersionCode bump

- ui/common/src/main/res/values/strings.xml
> New Strings - Rewards and Home

- ui/common/src/main/res/values/strings.xml
> New String - Manage Wallet

- ui/common/src/main/res/values/strings.xml
> New strings

- ui/common/src/main/res/values/strings.xml
> New String - PayPal error

- ui/common/src/main/res/values/strings.xml
> New strings - Verification

- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletFragment.kt
- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletViewModel.kt
Yes | No
Tickets related to this pull-request: [APPC-3679](https://aptoide.atlassian.net/browse/APPC-3679)
> List inactive wallets

- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroFragment.kt
- app/src/main/res/layout-land/fragment_verification_intro.xml
- app/src/main/res/layout/fragment_verification_intro.xml
- app/src/main/res/layout/fragment_verify_picker.xml
Yes | No
Tickets related to this pull-request: [APPC-3728](https://aptoide.atlassian.net/browse/APPC-3728)
> Update verify wallet strings according to the new copies

- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetEarningBonusUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/common/PurchaseBonusView.kt
- app/src/main/res/layout-land/payment_methods_layout.xml
- app/src/main/res/layout/payment_methods_layout.xml
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/Gamification.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/PromotionsRepository.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/entity/FakePromotionsRepository.kt
- legacy/gamification/src/test/java/com/appcoins/wallet/gamification/GamificationTest.kt
Fixed bonus value exhange in payment, topup, first payment flow. 
Fixed invisible layout bonus in payment flow
No
Try to make a purchase, first purchase and Top Up and see bonus value in each case
Tickets related to this pull-request: [APPC-3726](https://aptoide.atlassian.net/browse/APPC-3726)
> [BugFix/3726] Wrong Bonus value 

- app/src/main/java/com/asfoundation/wallet/promotions/ui/list/model/DefaultModel.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/list/model/ProgressModel.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/list/model/PromoCodeModel.kt
Fixed wrong function to get Current Time in Offset UTC to comparing and show correctly expired Date from user
No
Try changing your time and timezone and see if the expiration time doesn't change
Tickets related to this pull-request: [APPC-3727](https://aptoide.atlassian.net/browse/APPC-3727)
> [BugFix/3727] Wrong Parse Expired Date in Perks

- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroFragment.kt
- app/src/main/res/layout-land/fragment_verification_intro.xml
- app/src/main/res/layout/fragment_verification_intro.xml
- app/src/main/res/layout/fragment_verify_picker.xml
Reverts Catappult/appcoins-wallet-android#593
(will wait for translations)
> Revert "Update verify wallet strings according to the new copies"

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsFragment.kt
Always use Adyen Paypal on First Payment Flow.
No
> Use adyen Paypal on first payment flow

- ui/common/src/main/res/values/strings.xml
> New Strings - Manage wallet

- convention/src/main/java/com/appcoins/wallet/convention/Config.kt
- convention/src/main/java/com/appcoins/wallet/convention/plugins/AndroidAppPlugin.kt
- convention/src/main/java/com/appcoins/wallet/convention/plugins/AndroidLibraryPlugin.kt
Build variant support to have separate flavors for Aptoide and GP builds.
No
Before testing, do a Sync Project.
https://aptoide.atlassian.net/browse/APPC-3695
> [APPC-3695] Build variants support

- ui/common/src/main/res/values/strings.xml
> New String - AppCoins compatible games

- app/src/main/java/com/asfoundation/wallet/change_currency/ChangeFiatCurrencyFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsPresenter.kt
- feature/change-currency/data/src/main/java/com/appcoins/wallet/feature/changecurrency/data/use_cases/GetChangeFiatCurrencyModelUseCase.kt
- feature/change-currency/ui/src/main/java/com/appcoins/wallet/feature/changecurrency/ui/ChangeFiatCurrencyScreen.kt
Fixes two bugs with navigation and UI:
- After changing the currency, it no longer needs to back clicks on settings to go back home
- In landscape, the bottom sheet no longer has a weird appearance 
No
https://aptoide.atlassian.net/browse/APPC-3634
> Change currency bugs

- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletFragment.kt
- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletViewModel.kt
- ui/common/src/main/res/values/strings.xml
Yes | No
Tickets related to this pull-request: [APPC-3744](https://aptoide.atlassian.net/browse/APPC-3744)
> Manage Wallets: Create wallet bottom sheet

- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardViewModel.kt
- ui/common/src/main/res/values/strings.xml
- ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceCardComposable.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/NftCardComposible.kt
Fixes to the following new wallet design bugs: 
- _Inconsistência nos cards (Active promotions VS jogos vs NFT card)._
- _Quando um user não tem qualquer compra não aparecem as active promos, mas quando faço uma compra ou TopUp, tenho de fechar a app e voltar a entrar para me aparecerem os perks._
- _NFT card fica sobreposto quando o user é VIP e abre a wallet pela primeira vez, sendo que o card de VIP está a apontar para o botão da home._
- _Não há o título "AppCoins Compatible Games"_
No
Home and Rewards
Home and Rewards:
- Check with a VIP wallet. 
- Check on Aptoide build variant
https://aptoide.atlassian.net/browse/APPC-3743 …
> [APPC-3743] Bugfixes wallet refactor - 1

- ui/common/src/main/res/values-ko/strings.xml
- ui/common/src/main/res/values-tr/strings.xml
> Fixed String translate error

- app/build.gradle.kts
Updated versionCode to the last RC
> Version code 264

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/App.kt
- app/src/main/java/com/asfoundation/wallet/analytics/InitilizeDataAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/AnalyticsLabels.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeEventLogger.kt
Property device_orientation added to all events.
Fix package name.
No
See indicative logs in logcat
https://aptoide.atlassian.net/browse/APPC-3778
https://aptoide.atlassian.net/browse/APPC-3776
> [APPC-3776] Indicative landscape/portrait property; Fix package name

- legacy/skills/src/main/java/cm/aptoide/skills/SkillsAnalytics.kt
Renames eskills fragments, in analytics to ensure a difference between wallet and eskills events.
> Changes fragment names to ensure difference between events

- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsGamificationComposable.kt
Prevent crash on rewards if currentProgress and maxProgress equals to Zero
No
Tickets related to this pull-request: [APPC-3737](https://aptoide.atlassian.net/browse/APPC-3737)
> [BugFix/ APPC-3737] Crash on Gamification Head

- ui/common/src/main/res/values/strings.xml
> String update - Cancel subscription

- ui/common/src/main/res/values/strings.xml
> New Strings - Verify and TxID

- app/src/main/java/com/asfoundation/wallet/transactions/TransactionDetailsFragment.kt
- app/src/main/java/com/asfoundation/wallet/transactions/TransactionModel.kt
- app/src/main/java/com/asfoundation/wallet/transactions/TransactionUtils.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/TransactionResponse.kt
- ui/common/src/main/res/values/strings.xml
Added TxID, SKU.
Removed details url.
No
Open every transaction type.
https://aptoide.atlassian.net/browse/APPC-3806
> [APPC-3806] Transactions Details fields update

- app/src/main/java/com/asfoundation/wallet/onboarding/pending_payment/OnboardingPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetEarningBonusUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabInteract.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/util/OneStepTransactionParser.kt
- app/src/test/java/com/asfoundation/wallet/util/OneStepWatchedTransactionParserTest.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/ForecastBonusResponse.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/ForecastBonus.kt
- legacy/gamification/src/test/java/com/appcoins/wallet/gamification/GamificationTest.kt
Optimize web call usage in the payment flow for faster loading times.
No
Make any payment (and check if the bonus is correct).
Make an Onboarding payment and check if the bonus is correct.
Top-up and check if the bonus is correct.
https://aptoide.atlassian.net/browse/APPC-3811
> [APPC-3811] IAP Payment Flow Optimization Part 1

- ui/common/src/main/res/values/strings.xml
> String update - Twitter X

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/billing/gameshub/GamesHubBroadcastService.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalTopupFragment.kt
Locks rotation on topup to prevent fragment recreation.
No
https://aptoide.atlassian.net/browse/APPC-3818
> [APPC-3818] Fix duplicated topup

- app/src/main/res/layout/fragment_subscription_cancel.xml
- app/src/main/res/layout/fragment_subscription_details.xml
- app/src/main/res/layout/fragment_subscription_list.xml
- app/src/main/res/layout/layout_no_subscriptions.xml
- ui/common/src/main/res/values/styles_views.xml
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WalletButtonView.kt
> Fix Manage Subscriptions layout

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/billing/analytics/BillingAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/billing/gameshub/GamesHubBroadcastService.kt
For the GamesHub broadcast, changed the parameter from txid to uid.
No
https://aptoide.atlassian.net/browse/APPC-3755
> GamesHub Broadcast rename txid parameter to uid

- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletViewModel.kt
- feature/backup/data/src/main/java/com/appcoins/wallet/feature/backup/data/use_cases/BackupSuccessLogUseCase.kt
- feature/backup/data/src/main/java/com/appcoins/wallet/feature/backup/data/use_cases/SendBackupToEmailUseCase.kt
- feature/backup/ui/src/main/java/com/appcoins/wallet/feature/backup/ui/save_options/BackupSaveOptionsViewModel.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/balance/TokenBalance.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/balance/TokenValue.kt
Fix for backup to email.
Fix crash on balance bottom sheet when minimizing app.
No
> Fix backup to email request v3; Fix crash balance bottom sheet 

- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
> fix promotions list size

- app/src/main/res/layout/recover_entry_options.xml
> fix recover field color

- app/build.gradle.kts
version bump
No
https://aptoide.atlassian.net/browse/APPC-3857
> version code

- app/build.gradle.kts
> Bump version code v3

- legacy/skills/src/main/res/values/strings.xml
> New Strings - e-Skills games

- ui/common/src/main/res/values/strings.xml
> New String - Backup error

- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentView.kt
- app/src/main/java/com/asfoundation/wallet/topup/paymentMethods/TopUpPaymentMethodsAdapter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAdapter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsViewHolder.kt
- app/src/main/res/layout/item_payment_method.xml
Make PayPal billing agreement loading asynchronous as to not block the UI.
No
Make PayPal payments, log in, log out.
Tickets related to this pull-request: [APPC-3878](https://aptoide.atlassian.net/browse/APPC-3878)
> [APPC-3878] Implement Async PayPal loading

- ui/common/src/main/res/values/strings.xml
> New Strings - Invoice Download

- ui/common/src/main/res/values/strings.xml
> New strings - Change card

- ui/common/src/main/res/values/strings.xml
> New Strings - Backup confirmation

- app/build.gradle.kts
- app/src/debug/AndroidManifest.xml
- convention/build.gradle.kts
- convention/src/main/java/com/appcoins/wallet/convention/plugins/FirebasePlugin.kt
- gradle/libs.versions.toml
> Add crashlytics to app

- app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
> Fix main crash of GP console (binding)

- core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/model/TicketResponse.kt
- legacy/skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt
Fixes edge case when the ticket is cancelled before ticketId is initialized.
Buy ticket and before it shows "waiting for opponents" backpress to exit the flow. Check logs to see if no error occurred.
Tickets related to this pull-request: [ESKL-357](https://aptoide.atlassian.net/browse/ESKL-357)
> adds check for lateinit

- app/build.gradle.kts
> Version 274

- app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
- app/src/main/res/layout/recover_entry_options.xml
- app/src/main/res/layout/recover_password_info.xml
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WalletTextFieldView.kt
Fixed diff between layout and design
No
> Bugfix/ Recovery Layout Changes

- app/src/main/res/layout-land/recover_password_fragment.xml
- app/src/main/res/layout/change_active_wallet_bottom_sheet_layout.xml
- app/src/main/res/layout/gamification_info_bottom_sheet.xml
- app/src/main/res/layout/recover_password_fragment.xml
- ui/common/src/main/res/values/styles.xml
Conclude BugFixes VII
No
Tickets related to this pull-request: [APPC-3887](https://aptoide.atlassian.net/browse/APPC-3887)
[APPC-3887]: https://aptoide.atlassian.net/browse/APPC-3887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Bugfix/ APPC- 3887] BugFixes XII

- app/src/main/java/com/asfoundation/wallet/manage_wallets/RemoveWalletFragment.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsNavigator.kt
> Fix remove wallet crash

- app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
- app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt
Fixed Navigate back action inside Recovery Flow
No
> BugFix/ Recovery Navigate Back Error

- ui/common/src/main/res/values/strings.xml
> New Strings - Challenge Reward (DES-410)

- app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
- app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordFragment.kt
- app/src/main/res/navigation/recover_wallet_graph.xml
Fixed Recovery With Password Redirect Flow
No
> BugFix/ Recovery With Password Redirect Flow

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
Yes | No
Tickets related to this pull-request: [APPC-3895](https://aptoide.atlassian.net/browse/APPC-3895)
[APPC-3895]: https://aptoide.atlassian.net/browse/APPC-3895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-3895][Bug] fix verify button hidden on IAP

- app/src/main/AndroidManifest.xml
This PR was created because we need the wallet to have higher priority than GH, otherwise the payments will be always processed by GH.
No
Install GH on dev (I can provide a GH version with app links) env and run the command:
`adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "https://apichain.dev.catappult.io/transaction"`
Confirm that wallet had priority over GH.
> App priority to app links

- ui/common/src/main/res/values/strings.xml
> New string - First purchase

- app/src/main/java/com/asfoundation/wallet/App.kt
- app/src/main/java/com/asfoundation/wallet/di/temp_gradle_modules/BdsBillingModule.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetFirstPaymentMethodsUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/BrokerBdsApi.kt
- legacy/bdsbilling/build.gradle.kts
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BdsBilling.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingRepository.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
- legacy/billing/build.gradle.kts
- legacy/billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingReceiverActivity.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/BillingDependenciesProvider.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/BillingService.kt
Yes | No
Tickets related to this pull-request: [APPC-3892](https://aptoide.atlassian.net/browse/APPC-3892)
[APPC-3892]: https://aptoide.atlassian.net/browse/APPC-3892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-3892]Add OEM ID to payment methods

- app/build.gradle.kts
versionCode increase to 276
Yes | No
> Version bump 276

- app/src/main/java/com/asfoundation/wallet/billing/adyen/PaymentType.java
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/list/PaymentMethodClick.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/list/model/PaymentMethodModel.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/AsfInAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsMapper.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
- app/src/main/res/layout-land/fragment_top_up.xml
- app/src/main/res/layout-land/payment_methods_layout.xml
- app/src/main/res/layout/fragment_top_up.xml
- app/src/main/res/layout/payment_methods_layout.xml
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/BrokerBdsApi.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/Gateway.kt
Integrates Offer Wall (Challenge Reward) payment method for topUp and IAPs
No
Tickets related to this pull-request: [APPC-3894](https://aptoide.atlassian.net/browse/APPC-3894)
[APPC-3894]: https://aptoide.atlassian.net/browse/APPC-3894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-3894] Integrate Offer Wall Payment Method

- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- feature/challenge-reward/data/build.gradle.kts
- feature/challenge-reward/data/src/main/java/com/appcoins/wallet/feature/challengereward/data/presentation/CheckChallengeRewardPaymentMethodViewModel.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsActionsComposable.kt
Adds the Offer wall rewards card visibility component. This card should be visible if the offer wall payment method (Challenge Reward) is available as a payment method
No
Tickets related to this pull-request: [APPC-3907](https://aptoide.atlassian.net/browse/APPC-3907)
[APPC-3907]: https://aptoide.atlassian.net/browse/APPC-3907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-3907] Offer Wall Rewards visibility

- convention/src/main/java/com/appcoins/wallet/convention/plugins/AndroidAppPlugin.kt
> [Fix] Revert Minify

- app/build.gradle.kts
> Version 3.3.0 277

- app/build.gradle.kts
> bump version

- ui/common/src/main/res/values/strings.xml
> New String - Top-up bonus

- app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
Eskills Endgame osp call was not working properly.
isWalletFromBds was crashing due to lack of info in url, for endgame flow calls.
This PR removes isWalletFromBds from eskills logic
Yes | No
Tickets related to this pull-request: [ESKL-367](https://aptoide.atlassian.net/browse/ESKL-367)
[ESKL-367]: https://aptoide.atlassian.net/browse/ESKL-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixes issue with eskills endgame osp call

- app/build.gradle.kts
> Version Bump 279

- ui/common/src/main/res/values/strings.xml
> Strings Update - Gamification (APPC-3916)

- legacy/skills/src/main/res/values/colors.xml
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/TransactionsComposable.kt
Fix layout issues asked by design, namely rounded corners to app icons on transactions and statusbar color
No
open app and verify status bar color and verify an app icon on IAP transaction list and details
Tickets related to this pull-request: [APPC-3924](https://aptoide.atlassian.net/browse/APPC-3924)
[APPC-3924]: https://aptoide.atlassian.net/browse/APPC-3924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-3924] Fix layout issues

- app/build.gradle.kts
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/product/InappBillingApi.kt
> Version 281

- app/src/main/java/com/asfoundation/wallet/wallet_reward/GamificationHeaderModel.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
Remove Hardcoded verification on GamificationFragment
No
Tickets related to this pull-request: [APPC-3977](https://aptoide.atlassian.net/browse/APPC-3977)
[APPC-3977]: https://aptoide.atlassian.net/browse/APPC-3977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APCC-3977] Remove Hardcoded verification on GamificationFragment

- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalIABViewModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/res/layout/item_payment_method.xml
- app/src/main/res/layout/selected_payment_method.xml
after a purchase with Paypal V2, Paypal will show up as the default payment method. Option to logout was added to the pre-selected screen
No
https://aptoide.atlassian.net/browse/APPC-3774
> [APPC-3774] Pre-selection for Paypal V2

- app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
…ment
Fix Crash on BillingWebViewFragment, the biggest error on crashlytics
No
Tickets related to this pull-request: [APPC-3927](https://aptoide.atlassian.net/browse/APPC-3927)
[APPC-3927]: https://aptoide.atlassian.net/browse/APPC-3927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APCC-3927]: Fix Crash on BillingWebViewFragment 

- ui/common/src/main/res/values/strings.xml
> New string - Making purchase

- ui/common/src/main/res/values/strings.xml
> String amend - Spend

- ui/common/src/main/res/values/strings.xml
> New String (DES-411) VK Pay

- ui/common/src/main/res/values/strings.xml
> New Strings - DES-417 purchase fees

- ui/common/src/main/res/values/strings.xml
> New Strings - Purchase fees (DES-417)

- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Prevents two appc requests from being made in quick succession
No
https://aptoide.atlassian.net/browse/APPC-3987
> fix(APPC-3987) Prevent duplicated appc requests

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
If the "store credit card" slider was activated after editing the card fields, then the state of the slider wouldn't be considered
No
https://aptoide.atlassian.net/browse/APPC-3988
> fix(APPC-3988) Stored card option update

- app/src/main/java/com/asfoundation/wallet/home/usecases/GetGamesListingUseCase.kt
- app/src/main/java/com/asfoundation/wallet/repository/GamesRepository.kt
- app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- app/src/test/java/com/asfoundation/wallet/home/usecases/GetGamesListingUseCaseTest.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/GamesApi.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/GamesListingResponseItem.kt
- ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
- ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/OpenGameFunction.kt
- ui/widgets/src/gp/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
- ui/widgets/src/gp/java/com/appcoins/wallet/ui/widgets/OpenGameFunction.kt
Opens the action urls when clicking on the games bundle items.
No
https://aptoide.atlassian.net/browse/APPC-3848
> [APPC-3848] Action URLs for games bundle

- app/build.gradle.kts
> Version 3.3.3 (282)

- ui/common/src/main/res/values/strings.xml
> New String - Sandbox

- legacy/skills/src/main/res/values/strings.xml
> New Strings - e-Skills Error Messages

- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsView.kt
- feature/change-currency/data/src/main/java/com/appcoins/wallet/feature/changecurrency/data/FiatCurrenciesRepository.kt
- feature/change-currency/ui/src/main/java/com/appcoins/wallet/feature/changecurrency/ui/ChangeFiatCurrencyScreen.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/NoNetworkAlert.kt
Fix a crash when it try to fetch currencies without network connection
No
Clean data of the app -> create a new wallet -> turn off internet -> go to settings -> it should show a error, not crashing.
Go back to home -> turn on internet -> Go to settings -> it should show currencies list
Tickets related to this pull-request: [APPC-4005](https://aptoide.atlassian.net/browse/APPC-4005)
[APPC-4005]: https://aptoide.atlassian.net/browse/APPC-4005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4005] HotFix Crash on Settings when fetch currencies

- ui/common/src/main/res/values/strings.xml
> New Strings - Onboarding from web payment (DES-439)

- app/build.gradle.kts
> Version update 3.4.0

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/res/layout/fragment_iab_transaction_completed.xml
- app/src/main/res/layout/payment_methods_layout.xml
- ui/common/src/main/res/values/styles.xml
Fixes for merged layouts. Payments/Topups
No
https://aptoide.atlassian.net/browse/APPC-3963
> [APPC-3963] Fix merged layouts

- ui/common/src/main/res/values/strings.xml
> New Strings - Processing fees

- ui/common/src/main/res/values/strings.xml
> New string - VIP and biometric

- app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/promotions/model/VipReferralInfo.kt
- app/src/main/java/com/asfoundation/wallet/promotions/ui/vip_referral/PromotionsVipReferralFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardNavigator.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/VipReferralResponse.kt
- core/utils/android-common/src/main/java/com/appcoins/wallet/core/utils/android_common/DateFormatterUtils.kt
- gradle.properties
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsGamificationComposable.kt
Add expiration date to vip referral code message and fix vip bottom on RewardsFragment
No
Become a VIP and go to referral program, body message should include a expiration date
Tickets related to this pull-request: [APPC-4033](https://aptoide.atlassian.net/browse/APPC-4033)
[APPC-4033]: https://aptoide.atlassian.net/browse/APPC-4033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4033] Add expiration date to vip referral code message

- app/src/main/java/com/asfoundation/wallet/repository/TransactionsHistoryPagingSource.kt
- app/src/main/java/com/asfoundation/wallet/repository/TransactionsHistoryRepository.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/TransactionsApi.kt
Add lang code to TransactionsApi call to fix translation bug on transaction details
No
navigate to some transaction details, description should be in the same language of the device
Tickets related to this pull-request: [APPC-4014](https://aptoide.atlassian.net/browse/APPC-4014)
[APPC-4014]: https://aptoide.atlassian.net/browse/APPC-4014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APCC-4014]: Add lang code to TransactionsApi call to fix translation bug

- app/build.gradle.kts
> Dev Update 3.5.1

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/ExternalAppEnum.kt
- app/src/main/res/layout-land/webview_fragment.xml
- app/src/main/res/layout/webview_fragment.xml
- ui/common/src/main/res/drawable/ic_dana.xml
Adds support to Dana's app urls.
No
Make a Dana payment
https://aptoide.atlassian.net/browse/APPC-3973
> [APPC-4057] Dana payment new url scheme

- legacy/skills/src/main/AndroidManifest.xml
Adds support for Android 14 with foregroundServiceType Definition
No
Play a match with Android 14 device
Tickets related to this pull-request: [ESKL-383](https://aptoide.atlassian.net/browse/ESKL-383)
[ESKL-383]: https://aptoide.atlassian.net/browse/ESKL-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ESKL-383): add foregroundServiceType to BackgroundGameService

- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeePresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyPresenter.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/OemIdExtractorV2.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/PartnerAddressService.kt
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OemIdPreferencesDataSource.kt
Adds OemId to the payment Indicative events.
No
Use a oemid injected game and make a purchase.
https://aptoide.atlassian.net/browse/APPC-4045
> [APPC-4045] OemId to Indicative events

- app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet/home/HomeViewModel.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardViewModel.kt
Hidden promotions title and skeleton  when there is no active promotion 
No
Open wallet when there is no active promotion
Tickets related to this pull-request: [APPC-4085](https://aptoide.atlassian.net/browse/APPC-4085)
[APPC-4085]: https://aptoide.atlassian.net/browse/APPC-4085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix[APPC-4085] Hidden promotions title when there is no promotion 

- app/build.gradle.kts
> Version bump

- app/build.gradle.kts
> Version bump 294

- app/build.gradle.kts
> 3.11.1 (295)

- ui/common/src/main/res/values/strings.xml
> New Strings - Fees (DES-417)

- ui/common/src/main/res/values/strings.xml
> New Srings - VIP Program

- ui/common/src/main/res/values/strings.xml
> New Strings - Connection Error (DES-441)

- ui/common/src/main/res/values/strings.xml
> New Strings - VIP Program

- ui/common/src/main/res/values/strings.xml
> New Strings - Delete wallet confirmation

- app/src/main/java/com/asfoundation/wallet/billing/paypal/usecases/CreatePaypalTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/repository/VkPayRepository.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/usecases/CreateVkPayTransactionTopUpUseCase.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/usecases/CreateVkPayTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/topup/vkPayment/VkPaymentTopUpFragment.kt
- convention/src/main/java/com/appcoins/wallet/convention/extensions/BuildConfigExtension.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/VkPayApi.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/VkPayTransaction.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/VkTransactionResponse.kt
Support different VK merchant accounts depending on app store.
No
Pay with VK, merchant id will come from service.
https://aptoide.atlassian.net/browse/APPC-4084
> [APPC-4084] Different merchants support for VK Pay

- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/res/layout-land/adyen_credit_card_layout.xml
- app/src/main/res/layout-land/iab_error_layout.xml
- app/src/main/res/layout-land/support_error_layout.xml
- app/src/main/res/layout/activity_iab.xml
- app/src/main/res/layout/adyen_credit_card_layout.xml
- app/src/main/res/layout/adyen_credit_card_pre_selected.xml
- app/src/main/res/layout/dialog_buy_buttons_adyen_error.xml
- app/src/main/res/layout/fragment_paypal.xml
- app/src/main/res/layout/fragment_paypal_topup.xml
- app/src/main/res/layout/iab_error_layout.xml
Fix issues on errors layouts of IAP
No
test every error flow of IAP, paypal on IAP and Topup and sandbox.
Tickets related to this pull-request: [APPC-4145](https://aptoide.atlassian.net/browse/APPC-4145)
[APPC-4145]: https://aptoide.atlassian.net/browse/APPC-4145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4145] IAP layout fixes

- ui/common/src/main/res/values/strings.xml
> String Update - Space missing

- app/src/main/java/com/asfoundation/wallet/billing/paypal/usecases/CreatePaypalTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/repository/VkPayRepository.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/usecases/CreateVkPayTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/topup/vkPayment/VkPaymentTopUpFragment.kt
- convention/src/main/java/com/appcoins/wallet/convention/extensions/BuildConfigExtension.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/VkPayApi.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/VkPayTransaction.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/VkTransactionResponse.kt
Reverts Catappult/appcoins-wallet-android#861
> Revert "[APPC-4084] Different merchants support for VK Pay"

- ui/common/src/main/res/values/strings.xml
> New Strings - PayPal verification DES-459

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/PaymentType.java
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/OnboardingPaymentMapper.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/list/PaymentMethodClick.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/list/model/PaymentMethodModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetPaymentInfoModelUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsMapper.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
Remove all mentions to GiroPay on code
No
check if there are some code of giropay
Tickets related to this pull-request: [APPC-4149](https://aptoide.atlassian.net/browse/APPC-4149)
[APPC-4149]: https://aptoide.atlassian.net/browse/APPC-4149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4149] Remove GiroPay Code

- app/src/main/java/com/asfoundation/wallet/analytics/IndicativeInitializeWrapper.kt
- app/src/main/java/com/asfoundation/wallet/analytics/InitilizeDataAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/analytics/SaveIsFirstPaymentUseCase.kt
- app/src/main/java/com/asfoundation/wallet/app_start/AppStart.kt
- app/src/main/java/com/asfoundation/wallet/app_start/Repositories.kt
- app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryViewModel.kt
- app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordViewModel.kt
- app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/AnalyticsLabels.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeEventLogger.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/AnalyticsModule.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/AppStartPreferencesDataSource.kt
Identifies first payments vs regular payments.
No
https://aptoide.atlassian.net/browse/APPC-4156
> [APPC-4156] Indicative property for payment_funnel

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/PaymentType.java
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/OnboardingPaymentMapper.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/list/PaymentMethodClick.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/list/model/PaymentMethodModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetPaymentInfoModelUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsMapper.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
Remove all mentions to GiroPay on code
No
check if there are some code of giropay
Tickets related to this pull-request: [APPC-4149](https://aptoide.atlassian.net/browse/APPC-4149)
[APPC-4149]: https://aptoide.atlassian.net/browse/APPC-4149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4149] Remove GiroPay Code DEV

- ui/common/src/main/res/values/strings.xml
> String update - Remove days in VIP Program string

- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetViewModel.kt
- feature/promo-code/data/src/main/java/com/appcoins/wallet/feature/promocode/data/repository/PromoCodeRepository.kt
Change Bottom  Sheet to make an request for get last stats from promoCode and Remove saved Promocode if exipered
No
Add a promoco and wait to time for this promoCode change to expired and open BottomSheet
Tickets related to this pull-request: [APPC-4094](https://aptoide.atlassian.net/browse/APPC-4094)
[APPC-4094]: https://aptoide.atlassian.net/browse/APPC-4094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4094] Delete expired Promocode

- app/build.gradle.kts
> Dev update 3.13.0 

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/support/SupportMessagingService.kt
Fix intercom notification type filter
No
> [APPC-4005] Intercom notification type fix

- ui/common/src/main/res/values/strings.xml
> New String - Wallet One Error (APPC-4192)

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/main/splash/SplashExtenderFragment.kt
- app/src/main/java/com/asfoundation/wallet/main/splash/SplashExtenderViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/SetOnboardingVipVisualisationStateUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/ShouldShowOnboardVipUseCase.kt
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/CommonsPreferencesDataSource.kt
Fix visualisation logic of vip onboarding screen
No
with a regular account, became vip and test if the message appear
Tickets related to this pull-request: [APPC-4215](https://aptoide.atlassian.net/browse/APPC-4215)
[APPC-4215]: https://aptoide.atlassian.net/browse/APPC-4215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Hotfix][APPC-4215] Change VIP onboarding visualisation logic

- ui/common/src/main/res/values/strings.xml
> New Strings - Manage cards

- ui/common/src/main/res/values/strings.xml
> New String - Start again

- ui/common/src/main/res/values/strings.xml
> New Strings - Top up success page

- app/src/main/AndroidManifest.xml
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/GamesHubContentProviderService.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/PartnerAddressService.kt
If the GamesHub's content provider indicates that the game was installed from GamesHub, then uses GamesHub's oemid.
No
https://aptoide.atlassian.net/browse/APPC-4087
> [APPC-4087]: GamesHub content provider for attribution

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
- app/src/main/java/com/asfoundation/wallet/billing/googlepay/GooglePayWebFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/sandbox/SandboxFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABViewModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabNavigator.java
fix bug when user cancel payment on vk 
No
start a payment with VK in Russia and cancel the process in the middle
Tickets related to this pull-request: [APPC-4271](https://aptoide.atlassian.net/browse/APPC-4271)
[APPC-4271]: https://aptoide.atlassian.net/browse/APPC-4271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Hotfix][APPC-4271] Fix error on SDK when paying with VK

- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/FiatCurrenciesPreferencesDataSource.kt
- feature/change-currency/data/src/main/java/com/appcoins/wallet/feature/changecurrency/data/FiatCurrenciesRepository.kt
two error was introduced with change currencies features, a error when try to make a first purchase without wallet created and the prices with fees is not correct
No
1st. try make a purchase without creating a wallet before.
2nd. during a IAP, verify if fees are being summed into final price.
Tickets related to this pull-request: [APPC-4279](https://aptoide.atlassian.net/browse/APPC-4279)
[APPC-4279]: https://aptoide.atlassian.net/browse/APPC-4279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Hotfix][APPC-4279] Fix issue on first wallet creation and price without fees

- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
Fix a bug in payments with VK caused by sum fee and price 
No
Try to make a payment with VK pay
Tickets related to this pull-request: [APPC-4279](https://aptoide.atlassian.net/browse/APPC-4279)
[APPC-4279]: https://aptoide.atlassian.net/browse/APPC-4279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4279] Fix issue on payment with VK

- app/build.gradle.kts
> Bump version to 3.17.0

- ui/common/src/main/res/values/strings.xml
> Strings Amend - Typo (back up)

- ui/common/src/main/res/values/strings.xml
> Strings Amend - Typo (backup)

- app/build.gradle.kts
> Update build version

- app/build.gradle.kts
> Update version Code

- app/build.gradle.kts
> Update version to 3.18.1

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/billing/googlepay/GooglePayWebViewModel.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalIABViewModel.kt
- app/src/main/java/com/asfoundation/wallet/billing/sandbox/SandboxViewModel.kt
- app/src/main/java/com/asfoundation/wallet/home/usecases/DisplayChatUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/google_pay/OnboardingGooglePayViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultViewModel.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/localpayments/LocalTopUpPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/viewmodel/TransactionDetailViewModel.java
- app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
- feature/support/data/src/main/java/com/wallet/appcoins/feature/support/data/SupportInteractor.kt
- feature/support/data/src/main/java/com/wallet/appcoins/feature/support/data/SupportRepository.kt
Add new fields to help intercom identify users.
No
Tickets related to this pull-request: [APPC-4196](https://aptoide.atlassian.net/browse/APPC-4196)
[APPC-4196]: https://aptoide.atlassian.net/browse/APPC-4196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4196] identify intercom users v2

- app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABViewModel.kt
- app/src/main/res/layout/vk_payment_iab_layout.xml
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/VkDataPreferencesDataSource.kt
- feature/support/data/src/main/java/com/wallet/appcoins/feature/support/data/SupportRepository.kt
Fix an error reported by developers that happens when user go back to the game without do login after start a payment with vk pay
No
In Russia (VPN), try to make a purchase with VK and go back to app without do login
Tickets related to this pull-request: [APPC-4316](https://aptoide.atlassian.net/browse/APPC-4316)
[APPC-4316]: https://aptoide.atlassian.net/browse/APPC-4316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4316] Fix back handler when starting a VK payment

- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivityView.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
fix a crash on topup
No
Go to topup and leaves quickly, it should causes a crash on some devices, it should be fixed 
Tickets related to this pull-request: [APPC-4305](https://aptoide.atlassian.net/browse/APPC-4305)
[APPC-4305]: https://aptoide.atlassian.net/browse/APPC-4305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(APPC-4305): fix crash on topup

- ui/common/src/main/res/values/strings.xml
> New String - No payment methods available

- ui/common/src/main/res/values/strings.xml
> DES-502 - Fees and VAT

- ui/common/src/main/res/values/strings.xml
> New Strings - Payment methods not available

- ui/common/src/main/res/values/strings.xml
> DES-478 - New Strings - Transfer funds

- ui/common/src/main/res/values/strings.xml
> Strings update - Capitalization issues

- ui/common/src/main/res/values/strings.xml
> String amend - Added placeholder in fees

- app/src/main/java/com/asfoundation/wallet/manage_cards/ManageAdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/manage_cards/ManageAdyenPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/manage_cards/ManageCardSharedViewModel.kt
- app/src/main/java/com/asfoundation/wallet/manage_cards/ManageCardsFragment.kt
- app/src/main/java/com/asfoundation/wallet/manage_cards/ManageDeleteCardBottomSheetScreen.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
- app/src/main/res/layout/manage_adyen_payment_fragment.xml
- legacy/billing/src/test/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepositoryTest.kt
- ui/common/src/main/java/com/appcoins/wallet/ui/common/theme/Typography.kt
Processing result from success, fail, redirect, 3DS
No
> [APPC-4187] Multiple Cards: Processing result

- app/build.gradle.kts
> Version Code bump 311

- ui/common/src/main/res/values/strings.xml
> New Strings - Verify from web (DES-491)

- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultViewModel.kt
> [APPC-4331] Redirect to paypal verification 2

- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultNavigator.kt
> [APPC-4331] redirect to paypal verification 3

- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultNavigator.kt
- app/src/main/res/navigation/inner_payment_graph.xml
- app/src/main/res/navigation/nav_bar_graph.xml
- legacy/billing/src/main/java/com/appcoins/wallet/billing/ErrorInfo.kt
Yes | No
Tickets related to this pull-request: [APPC-4331](https://aptoide.atlassian.net/browse/APPC-4331)
[APPC-4331]: https://aptoide.atlassian.net/browse/APPC-4331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4331]: Fix navigation on onboarding payment

- app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
Yes | No
Tickets related to this pull-request: [APPC-4331](https://aptoide.atlassian.net/browse/APPC-4331)
[APPC-4331]: https://aptoide.atlassian.net/browse/APPC-4331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APPC-4331: Fix paypal navigation on TopUp

- app/src/main/java/com/asfoundation/wallet/manage_cards/ManageCardsFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/AnalyticsModule.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/manage_cards/ManageCardsAnalytics.kt
> [APPC-4187] Fix analytics multiple cards

- ui/common/src/main/res/values/strings.xml
> New String - Purchase legal disclaimer (DES-507)

- ui/common/src/main/res/values/strings.xml
> New Strings - APPC-C disclaimer

- app/build.gradle.kts
> Release 3.20.0 Dev update

- app/src/main/java/com/asfoundation/wallet/analytics/InitilizeDataAnalytics.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/success/PromoCodeSuccessBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/AnalyticsModule.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/rewards/RewardsAnalytics.kt
Analytics for promo code flow.
No
https://aptoide.atlassian.net/browse/APPC-4317
> [APPC-4317] Analytics Promo Code

- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabPresenter.kt
- app/src/main/res/layout-land/fragment_top_up.xml
- app/src/main/res/layout/fragment_top_up.xml
Add Refund Disclaimer in Top with rules and layouts changes
No
Open TopUp Inside Europe Zone to see the disclaimer text
Tickets related to this pull-request: [APPC-4365](https://aptoide.atlassian.net/browse/APPC-4365)
[APPC-4365]: https://aptoide.atlassian.net/browse/APPC-4365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4365] TopUp Refund Disclaimer

- ui/common/src/main/res/values/strings.xml
> New Strings - Mailing list (DES-494)

- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/code/VerificationCodePresenter.kt
> [APPC-4352] Fix error when wrong verification code is inserted

- app/build.gradle.kts
> Dev update 3.21.2

- app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
When the user inserted a wrong CVC, then the header and buy button would disappear.
https://aptoide.atlassian.net/browse/APPC-4391
> [APPC-4391] Topup wrong CVC fix

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/interact/DeleteWalletInteract.kt
- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletFragment.kt
- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletViewModel.kt
- app/src/main/java/com/asfoundation/wallet/manage_wallets/RemoveWalletFragment.kt
- app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultViewModel.kt
- app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyInteract.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnChainBuyInteract.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/CarrierInteractor.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/code/VerificationCodeInteractor.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/code/VerificationCodePresenter.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/credit_card/intro/VerificationIntroInteractor.kt
- app/src/main/java/com/asfoundation/wallet/verification/ui/paypal/VerificationPaypalViewModel.kt
- app/src/main/java/com/asfoundation/wallet/verification/usecases/MakeVerificationPaymentUseCase.kt
- app/src/main/java/com/asfoundation/wallet/verification/usecases/SetCachedVerificationUseCase.kt
- app/src/main/res/navigation/manage_wallet_graph.xml
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/BrokerVerificationPreferencesDataSource.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/verification/BrokerVerificationRepository.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/verification/VerificationStatusCompound.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/verification/VerificationType.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/verification/WalletVerificationInteractor.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BackupCardComposable.kt
Verification states for verify credit card or PayPal.
No
https://aptoide.atlassian.net/browse/APPC-4352
> [APPC-4352] Verification cancel and one more step states

- app/src/main/java/com/asfoundation/wallet/main/MainActivity.kt
- app/src/main/java/com/asfoundation/wallet/main/MainActivityNavigator.kt
- app/src/main/java/com/asfoundation/wallet/main/MainActivityViewModel.kt
- app/src/main/java/com/asfoundation/wallet/main/use_cases/GetCachedGuestWalletUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/BackupModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/CachedBackupRepository.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
- app/src/main/java/com/asfoundation/wallet/repository/CachedGuestWalletRepository.kt
- app/src/main/res/layout-land/fragment_onboarding.xml
- app/src/main/res/layout/fragment_onboarding.xml
- app/src/main/res/navigation/onboarding_graph.xml
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/CachedBackupApi.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedBackupResponse.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedGuestWalletResponse.kt
add buttons to verify wallet on onboarding
No
Tickets related to this pull-request: [APPC-4322](https://aptoide.atlassian.net/browse/APPC-4322)
[APPC-4322]: https://aptoide.atlassian.net/browse/APPC-4322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4322]: Add verification redirect on onboarding

- app/src/main/res/layout/onboarding_payment_result_fragment.xml
Fix loading visibility on onboarding result
No
Verify if after a payment with paypal or credit card on onboarding, there is a loading between the payment conclusion and the sucess/error message.
Tickets related to this pull-request: [APPC-4168](https://aptoide.atlassian.net/browse/APPC-4168)
[APPC-4168]: https://aptoide.atlassian.net/browse/APPC-4168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4168] Fix loading visibility on onboarding result

- app/src/main/java/com/asfoundation/wallet/analytics/InitilizeDataAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/AnalyticsLabels.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeAnalytics.kt
Adds flavor super property to Indicative.
No
https://aptoide.atlassian.net/browse/APPC-4370
> [APPC-4370] Analytics: flavor

- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
- app/src/main/res/layout/payment_methods_layout.xml
- app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
Fixed loading error and change rule forcing pré~selected methods to show refund disclaimer
No
Try to make a pré-selected purchase with app coins credit and credit card and see disclaimer and loadings
> hotfix(Refund Disclaimer) Wrong color in loading

- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
- app/src/main/res/layout-land/fragment_onboarding.xml
- app/src/main/res/layout-land/onboarding_value_propositions.xml
- app/src/main/res/layout/fragment_onboarding.xml
- app/src/main/res/layout/onboarding_value_propositions.xml
Fix design issues reported by Luis
No
Luis already verified that issues are fixed
Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-4354)
> [Bugfix][APPC-4354] Fix design issues on verify from web

- ui/common/src/main/res/values/strings.xml
> String update - common_or

- app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethod.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsViewHolder.kt
- app/src/main/res/layout/item_payment_method.xml
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/PaymentMethodEntity.kt
- ui/common/src/main/res/values/styles.xml
Shows a message from MS with the description of why a payment method is disabled.
**Database changed?** 
No
https://aptoide.atlassian.net/browse/APPC-4395
> [APPC-4326] Message description for disabled payment methods

- ui/common/src/main/res/values/strings.xml
> New String - Discord (APPC-4280)

- ui/common/src/main/res/values/strings.xml
> New String - Open banking generic error

- app/build.gradle.kts
> 3.23.1 Dev

- app/src/main/java/com/asfoundation/wallet/entity/TransactionBuilder.java
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/google_pay/OnboardingGooglePayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/local_payments/OnboardingLocalPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentViewModel.kt
- app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
Add params to make a payment on onboarding
No
Make a onboarding payment with SDK
Tickets related to this pull-request: [APPC-4386](https://aptoide.atlassian.net/browse/APPC-4386)
[APPC-4386]: https://aptoide.atlassian.net/browse/APPC-4386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4386] Onboarding payment SDK making payment

- app/src/main/java/com/asfoundation/wallet/entity/TransactionBuilder.java
- app/src/main/java/com/asfoundation/wallet/main/MainActivity.kt
- app/src/main/java/com/asfoundation/wallet/main/MainActivityViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/CachedTransactionRepository.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/GetResponseCodeWebSocketUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/GetWsPortUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/SetResponseCodeWebSocketUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentNavigator.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/adyen_payment/OnboardingAdyenPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/google_pay/OnboardingGooglePayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/local_payments/OnboardingLocalPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/SdkPaymentWebSocketListener.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentViewModel.kt
- app/src/main/res/navigation/onboarding_graph.xml
- app/src/main/res/xml/network_security_config.xml
- app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OnboardingPaymentSdkPreferencesDataSource.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenResponseMapper.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/PaymentModel.kt
Add web Socket in the end of onboarding payment
No
Finish web socket in onboarding payment
Tickets related to this pull-request: [APPC-4387](https://aptoide.atlassian.net/browse/APPC-4387)
[APPC-4387]: https://aptoide.atlassian.net/browse/APPC-4387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4387] Web socket onboarding payment

- ui/common/src/main/res/values/strings.xml
> New String - Bank transfer top-up

- ui/common/src/main/res/values/strings.xml
> New String - Bank transfer bonus

- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
This PR adds the wallet address to the payment methods request during top up
No
Open the top up flow. Check the payment methods request on logs to confirm that the wallet address is in the request.
Tickets related to this pull-request: [APPC-4433](https://aptoide.atlassian.net/browse/APPC-4433)
[APPC-4433]: https://aptoide.atlassian.net/browse/APPC-4433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4433] Add wallet address to payment methods request

- ui/common/src/main/res/values/strings.xml
> New Strings - VIP

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
Fixed wrong Currency in IAP Payment to show correct currency in landscape
No
Change your wallet currency to INR and try to make a payment without VPN and when you turn the screen after selecting the payment method, the currency will be wrong
Tickets related to this pull-request: [APPC-4474](https://aptoide.atlassian.net/browse/APPC-4474)
[APPC-4474]: https://aptoide.atlassian.net/browse/APPC-4474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4474] Wrong Currency Code in IAP Landscape

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/billing/paypal/PayPalIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/OnBackPressedListener.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/share/SharePaymentLinkFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/share/SharePaymentLinkFragmentView.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/share/SharePaymentLinkPresenter.kt
- app/src/main/res/layout-land/fragment_share_payment_link.xml
- app/src/main/res/layout/fragment_share_payment_link.xml
When going back on paypal and "ask someone to pay", then goes back to payment methods screen
No
https://aptoide.atlassian.net/browse/APPC-4165
> [APPC-4165] Back on Ask Someone to Pay and PayPal

- ui/common/src/main/res/values/strings.xml
> Strings amend - E-mail typo

- .idea/codeStyles/Project.xml
- app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet/home/HomeViewModel.kt
- feature/backup/ui/src/main/java/com/appcoins/wallet/feature/backup/ui/BackupAlertBottomSheetScreen.kt
- feature/backup/ui/src/main/java/com/appcoins/wallet/feature/backup/ui/save_options/BackupSaveOptionsScreen.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/ConfirmEmailCardComposable.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WelcomeEmailCardComposable.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/component/TextField.kt
Improve email layous and error message
No
Open wallet in home page and try to send an email in card
Tickets related to this pull-request: [APPC-4442](https://aptoide.atlassian.net/browse/APPC-4442)
[APPC-4442]: https://aptoide.atlassian.net/browse/APPC-4442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4442] Improve email layout

- app/src/main/java/com/asfoundation/wallet/analytics/IndicativeInitializeWrapper.kt
- app/src/main/java/com/asfoundation/wallet/analytics/InitilizeDataAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/AnalyticsLabels.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeAnalytics.kt
Adds a super property with the value of the dark/light mode of the OS.
No
https://aptoide.atlassian.net/browse/APPC-4478
> [APPC-4478] Indicative dark/light mode property

- app/build.gradle.kts
> 3.24.0 dev update

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/main/MainActivity.kt
- app/src/main/java/com/asfoundation/wallet/main/MainActivityNavigator.kt
- app/src/main/java/com/asfoundation/wallet/main/MainActivityViewModel.kt
- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragment.kt
- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragmentNavigator.kt
- app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarViewModel.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetViewModel.kt
- app/src/main/java/com/asfoundation/wallet/redeem_gift/bottom_sheet/RedeemGiftBottomSheetFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardNavigator.kt
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/navigation/reward_graph.xml
- convention/src/main/java/com/appcoins/wallet/convention/plugins/AndroidAppPlugin.kt
- core/arch/src/main/java/com/appcoins/wallet/core/arch/data/Navigator.kt
This PR opens the giftcard bottom sheet and adds the giftcard automatically to the text field.
Also cleaned up some code.
No
Open the app to validate that it opens normally.
Also use a deeplink to open the app. This can be done using the following prompt command:
`adb shell am start -W -a android.intent.action.VIEW -d "appcoins://giftcard?giftcard=12345"`
Tickets related to this pull-request: [APPC-4444](https://aptoide.atlassian.net/browse/APPC-4444)
[APPC-4444]: https://aptoide.atlassian.net/browse/APPC-4444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4444] Deeplink redeem giftcard

- app/src/main/java/com/asfoundation/wallet/billing/mipay/MiPayFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/mipay/MiPayNavigator.kt
- app/src/main/java/com/asfoundation/wallet/billing/mipay/MiPayViewModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/WebViewActivity.kt
Locked MiPay webview payment to portrait due to poor behavior on landscape from MiPay side.
No
Start a payment flow for MiPay. Test MiPay payments from games in different orientations.
Tickets related to this pull-request: [APPC-4492](https://aptoide.atlassian.net/browse/APPC-4492)
[APPC-4492]: https://aptoide.atlassian.net/browse/APPC-4492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4492] MiPay lock web view to open in portrait

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/promo_code/bottom_sheet/entry/PromoCodeBottomSheetFragment.kt
> 3.26.0 update

- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsPresenter.kt
Fixes the issue of the currency not updating in settings after the user changes his currency.
No
Open settings, change the currency, check if the currency presented in the settings screen is updating
https://aptoide.atlassian.net/browse/APPC-4339
> [APPC-4339] Change currency in settings fix

- ui/common/src/main/res/values/strings.xml
> New Strings - Bank transfer

- app/src/main/java/com/asfoundation/wallet/billing/true_layer/usecases/AddTrueLayerPaymentMessageUseCase.kt
Changes the message displayed at the payment method.
No
> [APPC-4326] New message string for True Layer

- ui/common/src/main/res/values/styles.xml
Fixes Jenkins build not founding resource.
> [Fix] Jenkins build

- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletFragment.kt
- app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletViewModel.kt
- app/src/main/java/com/asfoundation/wallet/manage_wallets/bottom_sheet/ManageWalletSharedViewModel.kt
Remove a interval request and extra request to updateWallet inside manage Wallet to fixed glitch in composes
No
go to the manage wallet screen and try to add, delete, backup, change name and verify wallet
Tickets related to this pull-request: [APPC-4338](https://aptoide.atlassian.net/browse/APPC-4338)
[APPC-4338]: https://aptoide.atlassian.net/browse/APPC-4338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4338] Manage wallet wallet fixed display glitch

- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/ActivePromoCodeComposable.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
Fixes the get button on promotions for small devices.
No
https://aptoide.atlassian.net/browse/APPC-4001
> [APPC-4001] Fix hidden get button on small devices

- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WelcomeEmailCardComposable.kt
Add testTag to send email to mailing list feature.
No
Validate that the test tags are settend on the home screen for the send email to mailing list feature.
Tickets related to this pull-request: [APPC-4545](https://aptoide.atlassian.net/browse/APPC-4545)
[APPC-4545]: https://aptoide.atlassian.net/browse/APPC-4545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4545] Automatic tests add ids to composables

- app/src/main/java/com/asfoundation/wallet/home/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/home/HomeViewModel.kt
- app/src/main/java/com/asfoundation/wallet/home/usecases/GetImpressionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/repository/ImpressionRepository.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/BackendApiModule.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/ImpressionApi.kt
- ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
- ui/widgets/src/gp/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
This PR adds a call endpoint when user interaction on GamesBundle
No
Scroll games Bundle inside Home
Tickets related to this pull-request: [APPC-4530](https://aptoide.atlassian.net/browse/APPC-4530)
[APPC-4530]: https://aptoide.atlassian.net/browse/APPC-4530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4530] Android MMP campaings call endpoint on interaction

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/iab/IabBaseFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/PaymentActivity.kt
- app/src/main/java/com/asfoundation/wallet/iab/PaymentActivityNavigator.kt
- app/src/main/java/com/asfoundation/wallet/iab/di/PaymentActivityNavigatorFactory.kt
- app/src/main/java/com/asfoundation/wallet/iab/domain/model/PurchaseData.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/res/layout/activity_payment.xml
- app/src/main/res/navigation/iab_graph.xml
This PR creates the new entry point for the new IAP flow and the PurchaseData model.
It also disconnects the previous flow.
No
Try to start the new payment flow. Should see a "Hello" label.
Tickets related to this pull-request: [APPC-4534](https://aptoide.atlassian.net/browse/APPC-4534)
[APPC-4534]: https://aptoide.atlassian.net/browse/APPC-4534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4534] New iap payment activity and purchase data

- app/src/main/java/com/asfoundation/wallet/iab/PaymentActivity.kt
- app/src/main/java/com/asfoundation/wallet/iab/PaymentActivityNavigator.kt
- app/src/main/java/com/asfoundation/wallet/iab/di/IAPModule.kt
- app/src/main/java/com/asfoundation/wallet/iab/domain/model/PurchaseData.kt
- app/src/main/java/com/asfoundation/wallet/iab/error/IABError.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/PurchaseUriParameters.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/UriParser.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/UriParserImpl.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/osp/OSPUriParserImpl.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/osp/exception/MissingDataParseException.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/res/navigation/iab_graph.xml
This PR adds the parser for the new IAP flow.
No
You can test by checking the purchaseData object in the MainFragment.kt
Tickets related to this pull-request: [APPC-4532](https://aptoide.atlassian.net/browse/APPC-4532)
[APPC-4532]: https://aptoide.atlassian.net/browse/APPC-4532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4532] IAP add OSP parser

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/iab/di/IAPModule.kt
- app/src/main/java/com/asfoundation/wallet/iab/domain/model/PurchaseData.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/PurchaseUriParameters.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/UriParserImpl.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/osp/OSPUriParserImpl.kt
- app/src/main/java/com/asfoundation/wallet/iab/parser/sdk/SDKUriParserImpl.kt
- legacy/billing/build.gradle.kts
- legacy/billing/src/main/java/com/appcoins/wallet/billing/BillingIntentBuilder.kt
This PR adds the parser for the new IAP SDK flow.
No
You can test by checking the purchaseData object in the MainFragment.kt
Tickets related to this pull-request: [APPC-4533](https://aptoide.atlassian.net/browse/APPC-4533)
[APPC-4533]: https://aptoide.atlassian.net/browse/APPC-4533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4533] IAP add SDK parser 

- app/src/main/java/com/asfoundation/wallet/iab/presentation/IAPBottomSheet.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/theme/Palette.kt
- app/src/main/java/com/asfoundation/wallet/iab/theme/Theme.kt
- app/src/main/java/com/asfoundation/wallet/iab/theme/Typography.kt
This PR adds the initial implementation for the palette of colors and typography.
No
Can't be tested yet on app. Just change primary color on code and check the bottom sheet preview.
Tickets related to this pull-request: [APPC-4544](https://aptoide.atlassian.net/browse/APPC-4544)
[APPC-4544]: https://aptoide.atlassian.net/browse/APPC-4544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4544] Add Palette of colors and Typography

- app/src/main/java/com/asfoundation/wallet/iab/FragmentNavigator.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainViewModel.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/verify/VerifyFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/verify/VerifyViewModel.kt
- app/src/main/res/navigation/iab_graph.xml
Created the fragment for the verify screen
No
Start the IAP flow. Navigate from the generic error screen into the verify error screen. click the buttons (support, verify and try again) to validate that navigate to the correct places
Tickets related to this pull-request: [APPC-4518](https://aptoide.atlassian.net/browse/APPC-4518)
[APPC-4518]: https://aptoide.atlassian.net/browse/APPC-4518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4518] IAP error verify wallet

- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/pending_payment/OnboardingPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
- core/utils/properties/src/main/java/com/appcoins/wallet/core/utils/properties/UrlPropertiesFormatter.kt
Adds language support to term&conditions and privacy policy.
No
test the link in:
- onboarding 
- onboarding payment
- settings
https://aptoide.atlassian.net/browse/APPC-4138
> [APPC-4138] Terms and Conditions and Privacy language support

- app/src/main/java/com/asfoundation/wallet/onboarding/CachedTransactionRepository.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/PendingPurchaseFlowUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/RestoreGuestWalletFlowUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/google_pay/OnboardingGooglePayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/google_pay/OnboardingGooglePayViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/local_payments/OnboardingLocalPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/local_payments/OnboardingLocalPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetCachedTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetOnboardingTransactionBuilderUseCase.kt
- app/src/main/java/com/asfoundation/wallet/util/OneStepTransactionParser.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedTransactionResponse.kt
- legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/PaymentModel.kt
Fixed bug when trying to make a first purchase with OSP in countries that did not have a guest wallet on the web
No
Try first purchase in Portugal with both types and in EUA with both types and normal start of wallet
Tickets related to this pull-request: [APPC-4570](https://aptoide.atlassian.net/browse/APPC-4570)
[APPC-4570]: https://aptoide.atlassian.net/browse/APPC-4570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4570] Onboarding payment not opening in OSP

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/app_start/AppStart.kt
- app/src/main/java/com/asfoundation/wallet/entity/TransactionBuilder.java
- app/src/main/java/com/asfoundation/wallet/onboarding/CachedTransactionRepository.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/PendingPurchaseFlowUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/google_pay/OnboardingGooglePayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/local_payments/OnboardingLocalPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetCachedTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/utils/OnboardingUtils.kt
- app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedTransactionResponse.kt
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OnboardingPaymentSdkPreferencesDataSource.kt
Hotfix for the "go back to the game" after onboarding payment for SDK integrations.
No
https://aptoide.atlassian.net/browse/APPC-4591
> [APPC-4591] Fix for new SDK onboarding flow going back to the game

- app/src/main/java/com/asfoundation/wallet/entity/TransactionBuilder.java
- app/src/main/java/com/asfoundation/wallet/util/OneStepTransactionParser.kt
- app/src/main/java/com/asfoundation/wallet/util/OneStepUriParser.kt
> [APPC-4591] Fix sdk Onboarding Payment

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/app_start/AppStart.kt
- app/src/main/java/com/asfoundation/wallet/entity/TransactionBuilder.java
- app/src/main/java/com/asfoundation/wallet/onboarding/CachedTransactionRepository.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/PendingPurchaseFlowUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/google_pay/OnboardingGooglePayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/local_payments/OnboardingLocalPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/mipay/OnboardingMiPayFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetCachedTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/utils/OnboardingUtils.kt
- app/src/main/java/com/asfoundation/wallet/util/OneStepTransactionParser.kt
- app/src/main/java/com/asfoundation/wallet/util/OneStepUriParser.kt
- app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedTransactionResponse.kt
- core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OnboardingPaymentSdkPreferencesDataSource.kt
> 3.29.1 dev update

- ui/common/src/main/res/values/strings.xml
> New Strings - Split top-up confirmation strings

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/entity/TransactionBuilder.java
- app/src/main/java/com/asfoundation/wallet/util/OneStepTransactionParser.kt
Adds the web socket port back into the onboarding conclusion
No
https://aptoide.atlassian.net/browse/APPC-4591
> [APPC-4591] First payment web socket fix

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/promotions/alarm/NotificationScheduler.kt
Removed alarm permissions from manifest
No
Buy a product to schedule the notification on a VIP account.
Tickets related to this pull-request: [APPC-4541](https://aptoide.atlassian.net/browse/APPC-4541)
[APPC-4541]: https://aptoide.atlassian.net/browse/APPC-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove alarm permission

- app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/PendingPurchaseFlowUseCase.kt
- fix Onboardings without price/currency
- fix Onboarding recover from web
No
https://aptoide.atlassian.net/browse/APPC-4596
> [APPC-4596] Onboarding fixes

- app/build.gradle.kts
> Dev update 3.29 (329)

- app/src/main/java/com/asfoundation/wallet/iab/presentation/BonusScreen.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/IABButtons.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/IABGenericError.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/icon/IcGift.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/icon/IcGiftDisabled.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/theme/Palette.kt
Addes the bonus banner.
No
Check the previews
Tickets related to this pull-request: [APPC-4512](https://aptoide.atlassian.net/browse/APPC-4512)
[APPC-4512]: https://aptoide.atlassian.net/browse/APPC-4512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4512] Add Bonus Details view

- app/src/main/java/com/asfoundation/wallet/iab/presentation/BonusScreen.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/PurchaseInfoScreen.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/theme/Palette.kt
Adds the skeletons for the banner
No
Check the previews.
Tickets related to this pull-request: [APPC-4522](https://aptoide.atlassian.net/browse/APPC-4522)
[APPC-4522]: https://aptoide.atlassian.net/browse/APPC-4522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4522] Preselect payment method skeleton

- app/build.gradle.kts
> Update dev 3.30

- app/src/main/java/com/asfoundation/wallet/iab/presentation/IAPPaymentMethodScreen.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/theme/Palette.kt
Add preselected payment method and its skeleton
No
Check the previews
Tickets related to this pull-request: [APPC-4514](https://aptoide.atlassian.net/browse/APPC-4514)
[APPC-4514]: https://aptoide.atlassian.net/browse/APPC-4514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4514] Preselected payment method

- app/build.gradle.kts
> Dev 3.30.1 update

- app/src/main/java/com/asfoundation/wallet/main/MainActivity.kt
- app/src/main/java/com/asfoundation/wallet/main/MainActivityNavigator.kt
- app/src/main/java/com/asfoundation/wallet/main/MainActivityViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/BackupModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
- app/src/main/java/com/asfoundation/wallet/repository/CachedGuestWalletRepository.kt
- app/src/main/res/navigation/onboarding_graph.xml
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeEventLogger.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedGuestWalletResponse.kt
Added new payment funnel to cached guest wallet endpoint to use it to calculate isFirstPayment.
No
Start the onBoarding flow. Check the indicative analytics to validate if its sending the correct payment funnel.
Tickets related to this pull-request: [APPC-4588](https://aptoide.atlassian.net/browse/APPC-4588)
[APPC-4588]: https://aptoide.atlassian.net/browse/APPC-4588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4588] Payment funnel send from web to android

- app/build.gradle.kts
> Version bump 3.31.0

- app/build.gradle.kts
> Dev update 3.31.1

- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
Fix payment funnel possible values.
No
Test flows on Onboarding
Tickets related to this pull-request: [APPC-4588](https://aptoide.atlassian.net/browse/APPC-4588)
[APPC-4588]: https://aptoide.atlassian.net/browse/APPC-4588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4588] Fix payment funnel possible values

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
> Dev update 3.31.2

- app/build.gradle.kts
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/TransactionsComposable.kt
Lineup for pending transaction animation.
https://aptoide.atlassian.net/browse/APPC-4581
> [APPC-4581] Design lineup pending transactions

- app/build.gradle.kts
> Dev update 3.31.4

- ui/common/src/main/res/values/strings.xml
> New Strings - New purchase flow

- ui/common/src/main/res/values/strings.xml
> Payment methods

- ui/common/src/main/res/values/strings.xml
> New Strings - Payment methods

- ui/common/src/main/res/values/strings.xml
> New String - Buy button

- ui/common/src/main/res/values/strings.xml
> New Strings - Copied and topup

- legacy/skills/src/main/res/values/strings.xml
> Deleted strings

- app/src/main/java/com/asfoundation/wallet/di/temp_gradle_modules/BdsBillingModule.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/IAPBottomSheet.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/IAPPaymentMethodScreen.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/PurchaseInfoScreen.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/WalletAsyncImage.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsUiState.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/pending_payment/OnboardingPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetFirstPaymentMethodsUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
- app/src/main/res/navigation/iab_graph.xml
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/PaymentMethodEntity.kt
- feature/challenge-reward/data/src/main/java/com/appcoins/wallet/feature/challengereward/data/presentation/ChallengeRewardVisibilityViewModel.kt
- feature/challenge-reward/data/src/main/java/com/appcoins/wallet/feature/challengereward/data/presentation/ViewModelProvider.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BdsBilling.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingThrowableCodeMapper.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
> [APPC-4573] Payment methods skeleton

- app/src/main/java/com/asfoundation/wallet/iab/domain/use_case/GetBalanceUseCase.kt
- app/src/main/java/com/asfoundation/wallet/iab/domain/use_case/GetPaymentMethodsUseCase.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragmentUiState.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainViewModel.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsUiState.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsViewModel.kt
- app/src/main/res/navigation/iab_graph.xml
> [APPC-4574] Add logic to fetch payment methods

- app/src/main/java/com/asfoundation/wallet/iab/FragmentNavigator.kt
- app/src/main/java/com/asfoundation/wallet/iab/IABView.kt
- app/src/main/java/com/asfoundation/wallet/iab/IabBaseFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/PaymentActivity.kt
- app/src/main/java/com/asfoundation/wallet/iab/payment_manager/PaymentManager.kt
- app/src/main/java/com/asfoundation/wallet/iab/payment_manager/domain/PaymentMethodInfo.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/IAPPaymentMethodScreen.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/WalletAsyncImage.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainFragmentUiState.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainViewModel.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsFragment.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsUiState.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/payment_methods/PaymentMethodsViewModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/InAppPurchaseInteractor.java
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsInteractor.kt
> [APPC-4576] Add payment methods navigation

- app/build.gradle.kts
> Dev update 3.32.0 (337)

- app/src/main/java/com/asfoundation/wallet/home/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/home/HomeViewModel.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/TopBarComposable.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WelcomeEmailCardComposable.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/component/TextField.kt
Fixes the update of the state of the composable
No
https://aptoide.atlassian.net/browse/APPC-4679
> [APPC-4679] Mailing list fix

- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
Fixes missing fields from Indicative.
No
https://aptoide.atlassian.net/browse/APPC-4688
> [APPC-4688] Fix missing analytics fields

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/billing/amazonPay/AmazonPayIABFragment.kt
- app/src/main/java/com/asfoundation/wallet/billing/amazonPay/AmazonPayIABViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/amazonPay/OnboardingAmazonPayFragment.kt
- app/src/main/java/com/asfoundation/wallet/topup/amazonPay/AmazonPayTopUpFragment.kt
fixes 3DS in charge permission purchases.
No
> [APPC-4465] Amazon 3DS fix

- app/src/main/java/com/asfoundation/wallet/iab/payment_manager/payment_methods/APPCPaymentMethod.kt
- app/src/main/java/com/asfoundation/wallet/iab/presentation/main/MainViewModel.kt
- core/utils/android-common/src/main/java/com/appcoins/wallet/core/utils/android_common/CurrencyFormatUtils.kt
Fix currency symbol order.
No
Start IAP flow. Check copies in different languages.
Tickets related to this pull-request: [APPC-4685](https://aptoide.atlassian.net/browse/APPC-4685)
[APPC-4685]: https://aptoide.atlassian.net/browse/APPC-4685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4685] IAP bottom sheet fix copies

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/billing/amazonPay/AmazonPayIABViewModel.kt
- app/src/main/java/com/asfoundation/wallet/billing/amazonPay/repository/AmazonPayRepository.kt
- app/src/main/java/com/asfoundation/wallet/billing/amazonPay/usecases/CreateAmazonPayTransactionTopUpUseCase.kt
- app/src/main/java/com/asfoundation/wallet/billing/amazonPay/usecases/CreateAmazonPayTransactionUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/amazonPay/OnboardingAmazonPayViewModel.kt
Fixes the guest_id field on transaction creation
No
https://aptoide.atlassian.net/browse/APPC-4439
> [APPC-4439] Fix wrong field for MMP on Amazon Pay

- app/build.gradle.kts
> Dev update 3.33.2

- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/product/SubscriptionBillingApi.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Fixes the /inapp/subscriptions request
No
https://aptoide.atlassian.net/browse/APPC-4698
> [APPC-4698] Get subscriptions SDK request fix

- app/build.gradle.kts
> set version code to 341 and version name to 3.34.0

- app/src/main/java/com/asfoundation/wallet/manage_cards/usecases/GetStoredCardsUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/usecases/GetPaymentInfoFilterByCardModelUseCase.kt
- core/network/base/src/main/java/com/appcoins/wallet/core/network/base/EwtAuthenticatorService.kt
- legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Fix missing checksum on getEwtAuthentication in EwtAuthenticatorService
No
Validate the IAP payment with APPC and transfer APPC from a wallet to another.
Tickets related to this pull-request: [APPC-4648](https://aptoide.atlassian.net/browse/APPC-4648)
[APPC-4648]: https://aptoide.atlassian.net/browse/APPC-4648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4648] Android push notifications ewt auth failing

- app/src/main/java/com/asfoundation/wallet/billing/true_layer/usecases/AddTrueLayerPaymentMessageUseCase.kt
- app/src/main/java/com/asfoundation/wallet/onboarding/pending_payment/OnboardingPaymentViewModel.kt
- app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetEarningBonusUseCase.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
- app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsInteractor.kt
- app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/GamificationApi.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/Gamification.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/PromotionsRepository.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/entity/FakePromotionsRepository.kt
- legacy/gamification/src/test/java/com/appcoins/wallet/gamification/GamificationApiTest.kt
- legacy/gamification/src/test/java/com/appcoins/wallet/gamification/GamificationTest.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
Add payment method to bonus forecast endpoint
No
Go to topup. Change payment method and validate the data.
Tickets related to this pull-request: [APPC-4689](https://aptoide.atlassian.net/browse/APPC-4689)
[APPC-4689]: https://aptoide.atlassian.net/browse/APPC-4689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4689] Android bonus forecast send payment method

- ui/common/src/main/res/values/strings.xml
> New Strings - New onboarding

- app/build.gradle.kts
> Dev update 3.35.0

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/ui/Erc681ReceiverPresenter.kt
- core/utils/android-common/src/main/java/com/appcoins/wallet/core/utils/android_common/extensions/ExtensionFunctionUtils.kt
The creation of the url was encoded in a format that could allow special characters not allowed in the url parameters. 
This fix encodes the parameters in url-safe base64.
No
https://aptoide.atlassian.net/browse/APPC-4692
> [APPC-4691] Fix WebView url encoding special characters

- app/src/main/java/com/asfoundation/wallet/ui/Erc681ReceiverPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentInterface.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/usecases/CreateWebViewPaymentOspUseCase.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/usecases/CreateWebViewPaymentSdkUseCase.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/EventSender.kt
Adds support for external bank apps in VK payments through the WebView.
No
https://aptoide.atlassian.net/browse/APPC-4731
> [APPC-4731] Support for external apps

- app/build.gradle.kts
> Dev update 3.36.1

- ui/common/src/main/res/values/strings.xml
> New Strings - Rebranding disclaimer

- app/build.gradle.kts
- core/network/base/src/main/java/com/appcoins/wallet/core/network/base/BaseApiModule.kt
- core/network/base/src/main/java/com/appcoins/wallet/core/network/base/EwtAuthenticatorService.kt
- core/network/base/src/main/java/com/appcoins/wallet/core/network/base/JwtAuthenticatorService.kt
- core/network/base/src/main/java/com/appcoins/wallet/core/network/base/interceptors/RenewJwtInterceptor.kt
- core/network/base/src/main/java/com/appcoins/wallet/core/network/base/session/SessionManager.kt
Fixes bug when switching between wallets, as the JWT could be spoiled.
No
https://aptoide.atlassian.net/browse/APPC-4134
> [APPC-4134] Support multiple wallets with JWT

- app/build.gradle.kts
> Dev update 3.37.1 (346)

- ui/common/src/main/res/external_strings/values/perks.po
> New String - Bonus in bank transfer

- app/build.gradle.kts
> Dev Update 3.37.2 (347)

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/transfers/TransferFundsFragment.kt
> [APPC-4502] Balance string update

- app/src/main/java/com/asfoundation/wallet/ui/Erc681Receiver.kt
Fixes iap launch when coming from a locked device
No
> Fix payment from lock screen

- app/src/main/java/com/asfoundation/wallet/home/HomeFragment.kt
- app/src/main/java/com/asfoundation/wallet/transactions/TransactionDetailsFragment.kt
- app/src/main/java/com/asfoundation/wallet/transactions/TransactionsListFragment.kt
- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/TransactionsComposable.kt
Remove APPC-c references and change  app name with transaction type
No
See transactions list and details
Tickets related to this pull-request: [APPC-4752](https://aptoide.atlassian.net/browse/APPC-4752)
[APPC-4752]: https://aptoide.atlassian.net/browse/APPC-4752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4752] Remove APPC-C  references

- app/src/main/java/com/asfoundation/wallet/home/HomeFragment.kt
Fixes line break on small devices.
No
https://aptoide.atlassian.net/browse/APPC-4796
> [APPC-4796] Fix banner line break

- app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsMapper.kt
- app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsModel.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/PartnerAddressService.kt
- core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/UserStatusResponse.kt
- legacy/gamification/src/main/java/com/appcoins/wallet/gamification/repository/BdsPromotionsRepository.kt
Allows the removal of partner perk for specific stores.
No
https://aptoide.atlassian.net/browse/APPC-4795
> [APPC-4795] Disable partner perk for specific stores

- app/build.gradle.kts
> Dev update 4.0.0

- ui/common/src/main/res/values/strings.xml
> New strings - App store screens

- ui/common/src/main/res/values/strings.xml
> New Strings - DES-594

- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentInterface.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/models/VerifyFlowWeb.kt
Adds the verify flow support to the web checkout.
No
https://aptoide.atlassian.net/browse/APPC-4805
> [APPC-4809] Verify flow web checkout

- app/src/main/res/drawable/background_rounded_styleguide_payments.xml
- ui/common/src/main/res/drawable/background_content_payments.xml
Fix iap Color
No
Fix Background Color in iap
> Fix background color in iap RC

- app/src/main/res/drawable/background_rounded_styleguide_payments.xml
- ui/common/src/main/res/drawable/background_content_payments.xml
>  Fix background Color iap

- app/src/main/java/com/asfoundation/wallet/ui/Erc681Receiver.kt
- app/src/main/java/com/asfoundation/wallet/ui/Erc681ReceiverPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/repository/PayFlowRepository.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/usecases/IsWebViewPaymentFlowUseCase.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/payflow/PayFlowApi.kt
Change web payment flow including new input vercode 
No
> Change Web Flow api to include the vercode input

- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/payflow/PayFlowApi.kt
Change query vercode to wallet_vercode
No
> Change query vercode to wallet_vercode

- app/build.gradle.kts
> Dev update 4.1.0

- app/build.gradle.kts
> Dev update 4.2.0

- ui/common/src/main/res/values/strings.xml
> New strings - DES-564

- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentActivity.kt
- core/network/base/src/main/java/com/appcoins/wallet/core/network/base/interceptors/UserAgentInterceptor.kt
Adds the Wallet app user-agent to the requests done in the webview.
No
https://aptoide.atlassian.net/browse/APPC-4875
> [APPC-4875] Android user-agent for Web Checkout.

- ui/common/src/main/res/values/strings.xml
> New String - Join

- app/build.gradle.kts
> Dev update 4.3.0

- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentActivity.kt
Deactivates the user-agent in the webview.
No
> [APPC-4816] Remove user-agent for webview

- legacy/billing/src/main/AndroidManifest.xml
- legacy/billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingReceiverActivity.kt
Changes launch mode to singleInstance for URI payments.
No
https://aptoide.atlassian.net/browse/APPC-4900
> [APPC-4900] SDK MLBB launchMode

- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentInterface.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentViewModel.kt
Add javascript interface and call savePromoCodeUseCase
No
Add a promocde in webPayment
Tickets related to this pull-request: [APPC-4846](https://aptoide.atlassian.net/browse/APPC-4846)
[APPC-4846]: https://aptoide.atlassian.net/browse/APPC-4846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPC-4846] Embedded Web Checkout | Promo Code Management

- app/build.gradle.kts
> Dev update 4.3.1

- app/build.gradle.kts
> Dev update 4.4.0

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
Fixes the repeated frequency on the card screen.
No
https://aptoide.atlassian.net/browse/APPC-4751
> [APPC-4751] Repeated subscription frequency fix

- app/build.gradle.kts
> Dev update 4.4.1

- app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentInterface.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentViewModel.kt
Removes the bonus text from the success screen for free trials.
No
https://aptoide.atlassian.net/browse/APPC-4751
> [APPC-4751] Fix. Remove bonus text from free trial

- app/build.gradle.kts
- app/src/main/java/com/asfoundation/wallet/App.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/GAEventLogger.kt
- core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/AnalyticsModule.kt
- gradle/libs.versions.toml
Integrates Google Analytics
No
https://aptoide.atlassian.net/browse/APPC-4817
> [APPC-4817] Google Analytics integration

- app/build.gradle.kts
> Dev update 4.5.0 (360)

- ui/common/src/main/res/values/styles.xml
Fixes margins for android 15+ devices.
No
https://aptoide.atlassian.net/browse/APPC-4984
> [APPC-4984] Fixes margins in Android 15+ devices

- app/build.gradle.kts
> Dev update 4.8.1

- app/src/main/java/com/asfoundation/wallet/ui/Erc681Receiver.kt
- app/src/main/java/com/asfoundation/wallet/ui/Erc681ReceiverPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
- app/src/test/java/com/asfoundation/wallet/feature_flags/topup/TopUpDefaultValueUseCaseTest.kt
- app/src/test/java/com/asfoundation/wallet/service/AccountWalletServiceTest.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/wallet/AccountWalletService.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/wallet/domain/RecoverEntryResult.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/wallet/domain/WalletKeyStore.kt
- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/wallet/usecases/RecoverEntryPrivateKeyUseCase.kt
Recovers the wallet from file for cloud gaming. With this recover flow, the user won't need to login twice in cloud gaming.
No
https://aptoide.atlassian.net/browse/APPC-4991
> [APPC-4991] Cloud gaming recover flow

- app/build.gradle.kts
> Dev update 4.9.0

- feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/wallet/AccountWalletService.kt
Removes unnecessary logs from cloud gaming restore wallet
Yes | No
> [APPC-4991] Removes unnecessary logs from cloud gaming restore

- app/src/main/java/com/asfoundation/wallet/ui/Erc681Receiver.kt
- app/src/main/java/com/asfoundation/wallet/ui/Erc681ReceiverPresenter.kt
- app/src/main/java/com/asfoundation/wallet/ui/Erc681ReceiverView.kt
- app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
Removes the "preparing your wallet" message when recovering a wallet on cloud gaming emulator
No
https://aptoide.atlassian.net/browse/APPC-4991
> [APPC-4991] Remove message on Cloud Gaming recover wallet

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/asfoundation/wallet/ui/webview_gamification/WebViewGamificationActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_gamification/WebViewGamificationViewModel.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_gamification/usecases/GenerateWebGamificationUrlUseCase.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
- app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardViewModel.kt
- core/utils/properties/src/main/java/com/appcoins/wallet/core/utils/properties/HostProperties.kt
- ui/common/src/main/res/anim/none.xml
- ui/common/src/main/res/values/styles.xml
New Gamification screen using a webview to open the Gamification web page.
No
https://aptoide.atlassian.net/browse/APPC-4894
> [APPC-4894] New Gamification

- app/src/main/java/com/asfoundation/wallet/billing/sandbox/SandboxViewModel.kt
- app/src/main/java/com/asfoundation/wallet/billing/sandbox/repository/SandboxRepository.kt
- app/src/main/java/com/asfoundation/wallet/billing/sandbox/usecases/CreateSandboxTransactionUseCase.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/BrokerBdsApi.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/SandboxApi.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/product/SubscriptionBillingApi.kt
- core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/SandboxTokenPayment.kt
adds support to Sandbox for subscriptions, and sandbox token payments.
No
https://aptoide.atlassian.net/browse/APPC-5008
> [APPC-5008] Sandbox payment method for subscriptions

- .idea/codeStyles/Project.xml
- app/src/main/java/com/asfoundation/wallet/ui/webview_gamification/WebViewGamificationActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_login/WebViewLoginActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentActivity.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/WebViewPaymentInterface.kt
- app/src/main/java/com/asfoundation/wallet/ui/webview_payment/models/CloseBehaviorConfig.kt
Web payments won't allow the webview to be closed during the payment processing loading.
No
https://aptoide.atlassian.net/browse/APPC-4838
> [APPC-4813] Web payments close policy

- ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceNewCard.kt
Fixes big translations from not fitting in balance buttons.
No
https://aptoide.atlassian.net/browse/APPC-5013
> [APPC-5013] Big translations not fitting in balance buttons
